### ISSUE TITLE
Draconic Evolution Client Crash

### ISSUE THREAD

**Issue by jusjudge** [brandon3055/Draconic-Evolution#1002] opened 2017-12-22 21:29 UTC
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.6.275
* Minecraft Forge version: 14.23.1.2570
* Mod Pack: Private Modpack (if applicable)

## Crash report
```
https://hastebin.com/ozuhogeyud.pl
```
For some reason when I start up my client it loads up fine and I am able to click on the world I want to play. Now when I start to move around for a few seconds my client freezes and I have to force close it or it automatically crashes on it's own.

**Comment by brandon3055** [comment] 2017-12-24 08:29
What makes you think this is DE? The only mod i see in the crash is chisel's connected textures mod.

**Comment by zISKo666** [comment] 2017-12-24 09:54
Same issue here.
It appeared when upgrading DE to 2.3.6.275
Downgrading DE to 2.3.5.269 and everything is fine again.

**Comment by tterrag1098** [comment] 2017-12-30 06:29
A very brief inspection of Block#shouldSideBeRendered (the place where the NPE occurs) shows that it could occur only if Block#getBoundingBox returns null, which is invalid. I can only assume that DE is doing this somewhere.

**Comment by brandon3055** [comment] 2018-01-05 17:42
This was caused by my placed items. Should be fixed in the latest build.

**Closed by brandon3055** 2018-01-05 17:42 UTC
