### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by rcistano** [brandon3055/Draconic-Evolution#136] opened 2015-08-08 18:31 UTC
When I first ran the mod it seemed to run without a problem, now when trying to load the game with DE as one of the mods the game crashes saying something about Java not working. When I take out DE it doesn't have the problem.

I love the mod if I am able to have it run without problems.

**Comment by Ianaver** [comment] 2015-08-12 03:25
sorry but we need the crash log in order to help as it holds much more detailed information on the matter. Post it on pastebin or http://paste.ubuntu.com/ and give us the URL to the page with the log

**Comment by rcistano** [comment] 2015-08-12 05:50
http://paste.ubuntu.com/12059654/

**Comment by Kolatra** [comment] 2015-08-12 06:45
OutOfMemory error. Give more memory to the game.

**Comment by rcistano** [comment] 2015-08-12 07:05
How do I do  that

**Comment by rcistano** [comment] 2015-08-12 07:35
I've tried many different ways to have more. my Minecraft just doesnt like DE as much as me. I dont have any problems with other mods not working.

**Comment by Ianaver** [comment] 2015-08-12 07:37
minecraft by default uses 512 MB which is often never enough especially with mods

in the launcher, go to edit profile (make sure that you have atleast 4GB of RAM or minecraft WILL crash!) and click the box that says "JVM argumentss", in most cases minecraft automatically sets 1 Gigabyte of RAM allocated  (if you have more than 4GB of RAM I recommend instead using 2G. if the box is checked and there is nothing in the box next to it, enter this: -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy (replace the 1 with 2 or 3 max if your system can handle it)

**Comment by rcistano** [comment] 2015-08-12 08:17
Guess I just miss out on this specific mod.

**Comment by rcistano** [comment] 2015-08-12 16:13
By the way it is NOT a lack of memory. The window that comes up after the crash has something to do with Java not working because I have DE as one of the mods. In the past I have had over 80 mods work without a problem. I take it down to 65 and try to add DE and BOOM! Java not working problem. I take out DE and OH MY!! no problem could be found.

Maybe you can get this fixed.

**Comment by Ianaver** [comment] 2015-08-12 18:08
dude, I am not the Dev, I am not a pro at java either, however that crash log was a out of memory crash (java.lang.OutOfMemoryError: Java heap space). You also have to remember that some mods use less RAM than others and this mod just happens to go past the "tipping point" and made java crash. Honestly I don't know what else to tell you because thats what java spat back at you... :/
Mind you, I may very well be wrong so please don't yell at me in the comments...

also, can you tell me exactly what that window says so maybe I can get a good idea of WTH is going on?

One last thing, I was not able to reproduce this issue at all unless I set my allocated RAM back to 512 MB

**Comment by Kolatra** [comment] 2015-08-12 18:21
I am not the dev, and I do have programming experience, which does not matter in this situation, but this problem is easily fixable by allocating more memory to the game. The crash log does not even point at Draconic Evolution. It literally says OutOfMemory error, so you need to allocate more memory to Minecraft.

**Comment by rcistano** [comment] 2015-08-12 18:22
It has 2G to work with

**Comment by Kolatra** [comment] 2015-08-12 18:23
Memory: 27336752 bytes (26 MB) / 523501568 bytes (499 MB) up to 523501568 bytes (499 MB)

It does not. Try increasing it.

**Comment by rcistano** [comment] 2015-08-12 18:35
It loads everything without a problem but when I arrive to the main menu it crashes and I get this message:

Java (TM) Platform SE Binary Has Stopped Working
A problem caused the program to stop working correctly.
Windows will close the program and notify you if  a solution is available.

Then it takes me back to the Minecraft Launcher. When I try to find a crash report there isn't anything there.

**Comment by Kolatra** [comment] 2015-08-12 18:38
How much memory did you give it?

**Comment by rcistano** [comment] 2015-08-12 18:39
it has 2G

**Comment by rcistano** [comment] 2015-08-12 18:46
I think I'm done fooling with this mod. Wish it was able to work as I liked what I saw and tested in my test world but now it isnt working.

**Comment by Oxosorrel** [comment] 2015-08-12 18:49
Your java arguments limit the memory available to minecraft. You are not giving it 2G. 

From your log:  

JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M


-Xmx512M means you're limiting yourself to 512M, not 2G of RAM. At some point while playing you simply run out of that 512M of ram. 

It doesn't matter what other flags you have Xmx sets max heap size you have available. Google it. 
https://docs.oracle.com/cd/E13150_01/jrockit_jvm/jrockit/jrdocs/refman/optionX.html

This is not related to this specific mod at all. You will get this error if you pile on other mods. 

Each mod adds classes, and often textures for in-game objects, and other handlers. Each of those things take a bit RAM. Some of these take RAM at load, others eat a more as the game goes on. You can only pile so many mods onto the game until 512M isn't enough. 

Adjust your java args in your launcher, or remove mods, those are your only options. There is nothing to fix in DE or any other mod that may cause this for you in the future.

**Comment by rcistano** [comment] 2015-08-12 18:56
I once had close to 100 mods without a problem.... I take it down to 65 and try to have DE and nothing but problems

**Comment by rcistano** [comment] 2015-08-12 18:56
Anyways, I'm done fooling with DE

**Comment by Oxosorrel** [comment] 2015-08-12 19:09
Number of mods doesn't mean much. There are hundreds of small mods that add only a block, or new colored pick axes. They don't take up much RAM at all. Then there are big mods that add lots of textures, complex AI and chew up RAM like candy. That's why most big packs recommend 3-4 gigs. 

 Yes DE is on the heavier side of RAM use, but its not alone. 

If you refuse to actually take the 10 seconds to asjust your java args to -Xmx2G or more, then good luck. There is literally isn't anything the developer can do.

You are complaining that you can't haul a 1000 tons of gold bars with small wheelbarrow.

**Comment by rcistano** [comment] 2015-08-12 19:14
I have changed and re-changed all that... DE does not work.... I have had no problems with Thermal Expansion, Thermal Foundation, Big Reactors, Mekanism and several dozen other mods.

**Comment by Kolatra** [comment] 2015-08-12 19:16
Then you need to provide another crash report after you increase the memory amount. This is NOT the fault of Draconic Evolution.

**Comment by rcistano** [comment] 2015-08-12 19:23
I took out every mod and put in DE... same problem

**Comment by Kolatra** [comment] 2015-08-12 19:24
I just looked at your original crash report, Draconic Evolution is not even loaded... Is there something you're not telling us?

**Comment by Oxosorrel** [comment] 2015-08-12 19:24
What did you set them to? How much RAM does your PC have, you can't set java args to higher than you physically have?

I have all those mods you mentioned,  and more (243 total mods) in my personal pack along side DE. 

My PC has 8 gigs of ram, and for java args I use the following and it works great: 

 -Xmx4G -Xms3G -XX:+UseConcMarkSweepGC -XX:MaxGCPauseMillis=50

**Comment by rcistano** [comment] 2015-08-12 19:27
my computer has 4G and Minecraft has 2G to work with.

Maybe my thing isnt right... What thing would you have for 2G?

**Comment by Oxosorrel** [comment] 2015-08-12 19:27
I have to ask, does your PC have only 2G of physical RAM?

**Comment by rcistano** [comment] 2015-08-12 19:31
System says "Installed Memory (RAM): 4.00 GB (2.43 GB usable)" This is 32bit Windows 7 Pro. When I had 64bit Windows 7 Pro, it would say something like "Installed Memory (RAM): 4.00 GB (3.00 GB usable)"

**Comment by Kolatra** [comment] 2015-08-12 19:32
Yeah the maximum memory for Java in 32-bit is around 2GB...

**Comment by rcistano** [comment] 2015-08-12 19:33
Should I go back to 64bit?

**Comment by Kolatra** [comment] 2015-08-12 19:33
Yes. Why are you even on 32-bit?

**Comment by rcistano** [comment] 2015-08-12 19:35
I had to reformat the HD and wasnt sure if the os was 32 or 64

**Comment by rcistano** [comment] 2015-08-12 19:37
I was on 64-bit and Minecraft was having problems so I thought it was because I was using 64-bit so I went to 32-bit

**Comment by rcistano** [comment] 2015-08-12 19:37
Now I know that I have to change the setting in the launcher

**Comment by Ianaver** [comment] 2015-08-12 19:38
did you have errors or can't create dump file or something long ago?

**Comment by rcistano** [comment] 2015-08-12 19:39
I got the computer from my brother becuase he didnt like it anymore and went to a all in one pc. So I was told to reformat to get rid of all his things and that I could have it. As usual he didnt have any of the software CDs so I had to go looking for drivers and such.

**Comment by Oxosorrel** [comment] 2015-08-12 19:40
Yeah, 64 bit OS and 64 bit Java... Otherwise you've got a gig of ram doing nothing. You may want to spring a few bucks and and get more ram. I'm guessing your rig is older, and older generation Ram is pretty cheap. 8 gigs of ram is cheap on eBay.

**Comment by rcistano** [comment] 2015-08-12 19:41
its about a 5 year old notebook

**Comment by Ianaver** [comment] 2015-08-12 19:42
Just make sure that you don't mix RAM types if you go for more RAM

**Comment by Ianaver** [comment] 2015-08-12 19:43
notebooks are not really worth taking apart to add RAM :(

**Comment by rcistano** [comment] 2015-08-12 19:44
No, they are not.  So I am stuck with 4G ram

**Comment by Ianaver** [comment] 2015-08-12 19:45
XD sorry for deleting that MSG, just allocate 1G of memory and you should be fine! That does sadly mean you have to be careful about putting too many mods that eat RAM like crazy though :/

**Comment by rcistano** [comment] 2015-08-12 19:46
if I go with the 64-bit I have about 3G RAM to work with

**Comment by Ianaver** [comment] 2015-08-12 19:48
I suggest no more than 2G if your system can handle that, windows tends to go through 2G really fast and will close MC if it gets too low

**Comment by rcistano** [comment] 2015-08-12 19:49
right now the only thing on here is the OS and Minecraft

**Comment by Ianaver** [comment] 2015-08-12 19:50
still, just be careful of how much you allocate

**Comment by rcistano** [comment] 2015-08-12 19:50
my notebook has 4G RAM and with the 64-bit it says usable is 3G

**Comment by Ianaver** [comment] 2015-08-12 19:50
after all, your system needs RAM too!

**Comment by rcistano** [comment] 2015-08-12 19:51
OK, well I guess im in for a long re-format/re-setup, lol

**Comment by Ianaver** [comment] 2015-08-12 19:51
just reboot and insert a 64x disk and it will move your old stuff to windows.old

**Comment by Ianaver** [comment] 2015-08-12 19:52
that is unless you reformat

**Comment by rcistano** [comment] 2015-08-12 19:52
Really?

**Comment by Ianaver** [comment] 2015-08-12 19:53
yup! I am a PC tech, I did this before several times!

**Comment by rcistano** [comment] 2015-08-12 19:54
OK, thanks guys. Hopefully sometime soon I'll be rolling around with DE as a mod.

**Comment by Ianaver** [comment] 2015-08-12 20:00
good luck!

**Comment by Oxosorrel** [comment] 2015-08-12 20:07
Happy modding to you. With some luck, careful java args, and just the right ammount of mod selection, hopefully your system doesn't cry for mercy.  I hope it works for ya!

**Comment by rcistano** [comment] 2015-08-12 20:11
BTW any of you know of a mod that will wirelessly transport items (Excluding Ender Chest)

**Comment by Ianaver** [comment] 2015-08-12 20:17
how exactly? pipes? Backpacks? Thermal expansion has tessaracts for all forms of wireless transport (no players though, just items, fluids and energy)

**Comment by Oxosorrel** [comment] 2015-08-12 20:19
Thermal expansion (tresseract)
Enderio (dimensional transever)
AE2 (quantum link bridge)
I think RFtools has something similar. 
Pneumaticcraft drones fly items places
Random things and flaxbeard steam have cannons that shoot items to a target location. 
Mystcraft portals + railcraft carts. 

I'm sure there are others.

**Comment by rcistano** [comment] 2015-08-12 20:20
Well thanks for the list. I'll check those out

**Comment by rcistano** [comment] 2015-08-12 20:21
Sorry, Ianaver, I deleted my post while you added yours

**Comment by rcistano** [comment] 2015-08-12 20:35
How do I work the dimensional transever?

**Comment by Oxosorrel** [comment] 2015-08-12 20:47
I know it exists, I never mentioned I know how to use it ;)

Hit up some wikis or enderio mod spotlight youtubes. Part of the fun is figuring out new toys.

**Comment by rcistano** [comment] 2015-08-12 20:48
You have to power the things, lol

**Comment by Ianaver** [comment] 2015-08-12 20:51
meh, extra utils has some insane generators to power them!

**Comment by rcistano** [comment] 2015-08-12 20:53
I dont have problems with power, lol... I just had problems with transporting items wirelessly. Didnt want to make tunnels to transport items every where

**Comment by Ianaver** [comment] 2015-08-12 20:56
yeah lol

**Comment by rcistano** [comment] 2015-08-15 06:46
I now have Windows 7 Pro 64-bit, with Java 64-bit. 

I am loading up Minecraft with DE as one of the mods. Hope this works.

**Comment by brandon3055** [comment] 2015-08-16 05:21
Ok so got about half way through this thread and decided to just skip to the end so forgive me if i mention anything you have already tried.

Problem 1 is memory. According to your first crash report your ram was set to 510MB but it looks like you have fixed that.

Problem 2 currently when everything finishes loading and you get to the main menu DE reloads the texture manager which makes the game freeze for a few seconds (some factors can make it freeze for a lot longer) during this time windows sees the program as unresponsive. Normally windows dosnt really do anything about it with the exception of sometimes giving you the OPTION to close the program. But in your case it sounds like windows is automatically closing the program before it has a chance to unfreeze. If that is the case i have no idea how to change that BUT in the next version DE will no longer freeze the menu which should fix the issue completely.

**Comment by rcistano** [comment] 2015-08-16 07:19
OK

**Comment by rcistano** [comment] 2015-08-17 19:01
Snapshot?

**Comment by Ianaver** [comment] 2015-08-17 19:10
No, there is no need for a snapshot here. Your issue was with memory mainly and possibly windows is closing MC before it has a chance to load fully because of the freeze while textures are reloaded.

**Comment by rcistano** [comment] 2015-08-17 19:33
OKAY, I have included the new release of DE into my mods. Loaded up the game. Sat at the Main Menu a few seconds, no problem. make a new test world to build the energy storage. when I lay down the first block, BOOM, CRASH!

I am not sure how to read these crash reports but it's here: http://paste.ubuntu.com/12111125/

**Comment by Ianaver** [comment] 2015-08-17 20:05
ok, sorry... :( I don't know what to tell you anymore....

**Comment by rcistano** [comment] 2015-08-17 20:09
Any idea what caused the crash?

**Comment by GreatOrator** [comment] 2015-08-17 20:28
So from a non-professional viewpoint, it looks like the changes in energy reporting from the energy storage may be the cause.  Will wait for brandon to confirm or deny.

Try starting up a fresh world and see if you can build and store energy and let us know what happens

**Comment by rcistano** [comment] 2015-08-17 20:33
OK, I'll try again. Maybe it was just a one thing fluke.

**Comment by GreatOrator** [comment] 2015-08-17 20:34
If you do get the same crash, paste a link here and I'll make sure brandon sees it.  Keep in mind it is still early morning where he lives :)

**Comment by rcistano** [comment] 2015-08-17 20:39
I try to put down the Energy Core in my Test World and crash.

Once again, I have no idea how to read these crash reports. Here it is: http://paste.ubuntu.com/12111803/

**Comment by rcistano** [comment] 2015-08-17 20:41
This is not an urgent thing that needs to be fixed NOW. when ever he gets to it and releases a new version. I have no problem waiting.

**Comment by brandon3055** [comment] 2015-08-17 22:54
Sorry about that i will release a new snapshot ASAP because that wont just effect you...

**Comment by Ianaver** [comment] 2015-08-17 23:06
oh that type of snapshot... I am such a derp... XD

**Comment by rcistano** [comment] 2015-08-18 00:30
http://paste.ubuntu.com/12114781/

**Comment by brandon3055** [comment] 2015-08-18 02:10
Sorry about that i for got that i will also need to upload a new version of the core for this fix. Will be uploaded shortly.

**Comment by rcistano** [comment] 2015-08-18 02:13
lmao, im just excited that I am getting closer to be able to play with the mod

**Comment by brandon3055** [comment] 2015-08-18 02:15
Ok may take a minute to get approved but 1.0.0.6 is now on curse

**Comment by rcistano** [comment] 2015-08-18 02:22
I'll let you know when I get the release and If the mod is working on my end.

**Closed** 2015-08-18 03:21 UTC
Labels: bug

**Comment by Player142Studios** [comment] 2022-10-05 11:41
i also got a crash

https://pastebin.ubuntu.com/p/Js43vs9MFg/plain/

**Comment by Tahakk** [comment] 2022-10-05 12:32
Make a new issue, this one is 7 years old, also post the log somewhere where login is not required
