### ISSUE TITLE
Server crash when trying to resurrect the ender dragon

### ISSUE THREAD

**Issue by JPyro** [brandon3055/Draconic-Evolution#94] opened 2015-05-17 04:53 UTC
so currently on the server i play on when trying to do the resurrection for the ender dragon, the server crashes i tried duplicating it in single player, and i did, any time trying to resurrect the ender dragon my client crashes as well here is the pastbin of the crash any help would be great to find out what is wrong or what i am doing wrong lol

http://pastebin.com/Chq3juSH

we are using version - DRACONIC-EVOLUTION-1.7.10-V1.0.1

**Comment by brandon3055** [comment] 2015-05-17 07:58
I will look into it but i can tell you from the report that it seems to be some sort of conflict with the mod "sprinkles for vanilla" when the ritual tries to spawn the dragon.

**Comment by brandon3055** [comment] 2015-05-17 08:19
Not sure what it is about that mod but i cant even get it to run properly in my dev environment without throwing all sorts of errors (before i can even try the ritual). That makes it a bit tricky to figure out what the problem is. I suggest you also report this issue to the sprinkles for vanilla author.

https://github.com/VikeStep/sprinkles_for_vanilla

**Comment by JPyro** [comment] 2015-05-17 21:47
yea taking sprinkles for vanilla out fixed the crash lol

**Comment by brandon3055** [comment] 2015-05-17 22:13
Good news this is already fixed in sprinkles for vanilla 
https://github.com/VikeStep/sprinkles_for_vanilla/issues/31

**Closed by brandon3055** 2015-05-17 22:13 UTC
