### ISSUE TITLE
crash when shift clicking cores into fusion table

### ISSUE THREAD

**Issue by resinate** [brandon3055/Draconic-Evolution#1221] opened 2018-12-14 14:52 UTC
## Base information
* Minecraft version: 1.12.2
* Mod version: Draconic-Evolution-1.12.2-2.3.17.321-universal
* Minecraft Forge version: forge 14.23.5.2795
* Mod Pack: (if applicable) skyworlds

---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.12.2-0.5.43.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-87.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b161.jar)
  JEIDLoadingPlugin (JustEnoughIDs-1.0.2-26.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.2.4.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  StructureUtilsASM (StructureUtils-1.1.0.4.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.1.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 12/14/18 6:47 AM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at com.brandon3055.draconicevolution.client.gui.GuiFusionCraftingCore.func_146976_a(GuiFusionCraftingCore.java:186)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:75)
	at com.brandon3055.brandonscore.client.gui.modulargui_old.ModularGuiContainer.func_73863_a(ModularGuiContainer.java:169)
	at com.brandon3055.draconicevolution.client.gui.GuiFusionCraftingCore.func_73863_a(GuiFusionCraftingCore.java:287)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- Head --
Thread: Client thread
Stacktrace:
	at com.brandon3055.draconicevolution.client.gui.GuiFusionCraftingCore.func_146976_a(GuiFusionCraftingCore.java:186)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:75)
	at com.brandon3055.brandonscore.client.gui.modulargui_old.ModularGuiContainer.func_73863_a(ModularGuiContainer.java:169)
	at com.brandon3055.draconicevolution.client.gui.GuiFusionCraftingCore.func_73863_a(GuiFusionCraftingCore.java:287)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)

-- Screen render details --
Details:
	Screen name: com.brandon3055.draconicevolution.client.gui.GuiFusionCraftingCore
	Mouse location: Scaled: (357, 198). Absolute: (1071, 483)
	Screen size: Scaled: (640, 360). Absolute: (1920, 1080). Scale factor of 3

**Comment by brandon3055** [comment] 2018-12-16 07:46
Will be fixed in the next update. In the mean time don't press shift while you have that gui open. The crash is caused by addition information that is displayed while holding shift (mainly just the craft progress gets a couple decimal points) I suspect there is a moment just as the crafting begins where the gui recipe state is invalid. Holding shift at this time will cause you to crash.

**Closed** 2019-02-12 12:21 UTC
