### ISSUE TITLE
Disabling "place item in world" feature

### ISSUE THREAD

**Issue by NIK220V** [brandon3055/Draconic-Evolution#328] opened 2016-05-31 15:26 UTC
## Description
There in no option in config to disable "place item in world" possibility. 
I need it badly. Players on my server are just placing items everywhere using this feature.

## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: 10.13.4.1541
* Draconic Evolution version: 1.0.2-snapshot_5

**Comment by GreatOrator** [comment] 2016-05-31 16:10
What would stop them from placing random block normally?

**Comment by NIK220V** [comment] 2016-05-31 16:11
I don't want to prevent them from placing BLOCKS. I want to prevent them from placing ITEMS as blocks on the ground.

**Comment by GreatOrator** [comment] 2016-05-31 16:12
Well, same difference really, might make the change for 1.9, but not really seeing any difference between placing the items down or blocks randomly

**Comment by NIK220V** [comment] 2016-05-31 16:14
The thing is that players can place items with this feature ANYWHERE (ignoring vanilla or plugin restrictions). They block the spawnpoint so new players can play. (But protection works fine with BREAKING these placed items)

**Comment by GreatOrator** [comment] 2016-05-31 16:16
That is a different issue then.  If it is ignoring restrictions from mods/plugins, that is something to look into and what you should have mentioned to begin with.

So @brandon3055 the issue is the placement function bypasses plugin restrictions while placing.  Needs to be looked into so it respects things like towny, etc.

**Comment by brandon3055** [comment] 2016-06-01 02:37
This will be fixed in the next update, I will add a block placed event so other mods/plugins can prevent it from being placed.

**Closed by brandon3055** 2016-06-01 02:37 UTC
Labels: bug
