### ISSUE TITLE
|1.12| Cryo-Stabilized Fluxduct and Energy Pylon

### ISSUE THREAD

**Issue by Bass2style** [brandon3055/Draconic-Evolution#882] opened 2017-08-24 16:51 UTC
## Description
cryo-stabilized fluxducts aren't connecting to the pylons, but other Thermal Dynamics ducts will connect correctly

## Base information
* Minecraft version: 1.12
* Minecraft Forge version: 14.21.1.2443
* DE Version : 2.3.3.261
* Mod Pack: RagnaMod IV

## Crash report
no report availlable. but first reported here : https://github.com/CoFH/Feedback/issues/497

**Comment by Virtmo** [comment] 2017-09-03 13:31
Did you check pylon and glass is placed right? If pylon is above the center of energy core glass needs to be under under and vice versa. If it is not placed correctly cryo-stabilizied duct can not connect to pylon.

**Comment by Bass2style** [comment] 2017-09-03 15:22
well, without touching anything, after few days, energy transfert works now, the only thing that remains, is a "graphic issue", cable is graphicly not connected, but with a lot of magic, my setup is now working. Minecraft Rules. xD

**Comment by brandon3055** [comment] 2017-09-12 11:16
This "may" be fixed in the latest version as i implemented the missing forge energy capability. Though that really should not have been an issue.

**Comment by brandon3055** [comment] 2017-09-12 11:16
Actually i will leave this open so you can let me know if the issue is fixed with the latest version.

**Closed** 2017-10-23 21:11 UTC
