### ISSUE TITLE
Flux Capacitors discharging form 256M RF to 0 RF 1.10.2-2.1.0.232 

### ISSUE THREAD

**Issue by sintaxcz** [brandon3055/Draconic-Evolution#781] opened 2017-06-12 15:51 UTC
## Description
Flux Capacitors discharging form 256M RF to 0 RF with other mods chargeable items (example: AE2 wireless terminal,chageable weapons,tools etc.)

## Base information
* Minecraft version:1.10.2
* Minecraft Forge version:12.18.3.2281
* Brandon's Core:1.10.2-2.1.8.107

## Crash report
```
CRASH REPORT HERE
```

**Comment by Lukas45** [comment] 2017-06-13 22:17
Confirmed, Draconic Flux Capacitor went from 640M RF to 0 in about a second when holding the AE2 Wireless Terminal, even when not used and the Wireless Terminal being at full Energy (Doesn't charge Dark Steel tools, but it seems to be due to lack of Tesla API in our pack)

**Comment by brandon3055** [comment] 2017-06-13 22:55
This is a bug in the AppliedEnergistics energy capability. There item simply accepts any and all energy you the capacitor offers it (I have confirmed this in dev) i believe this is due to the fact that AE2's energy net works a little backwards compared to RF. With RF whenever energy is transferred the value returned by the transfer method is the amount that was transferred. With AE its the amount that was NOT transferred, So it looks like they are just missing the necessary conversion in their capability.

There is nothing i can do about this on my end. I suggest you post an issue on the AE github and feel free to reference this issue.

**Closed** 2017-07-07 12:18 UTC
