### ISSUE TITLE
Disabled Conduits on Energy Pylons still connected

### ISSUE THREAD

**Issue by AstroxV** [brandon3055/Draconic-Evolution#506] opened 2016-12-28 17:53 UTC
Putting a connected EnderIO energy conduit connected to an Energy Pylon in disabled state will still keep it connected. Also disabling it with a redstone signal is not working.

How to replicate:
Make a simple Energy Core with Stabilizers of Draconic Evolution and store some energy in it.
Then take a Capacitor and place it 2 block away from a Energy Pylon, connect the two with conduits. Energy will start filling up the Capacitor. Now use the Yeta Wrench to set the conduit that connects to the Energy Pylon to Disabled so it will disconnect from the pylon, and you will see that energy will keep flowing to the Capacitor.

Version: 2.0.4.142

**Comment by brandon3055** [comment] 2017-02-06 17:23
I can not reproduce this issue http://ss.brandon3055.com/loaoofi.png
If this was an issue at one point it mat have been fixed by EIO because this could really only have been an issue on their end.

**Closed by brandon3055** 2017-02-06 17:23 UTC
