### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by barsch** [brandon3055/Draconic-Evolution#72] opened 2015-04-17 20:13 UTC
I just got kicked the fifth time from my FTB Infinity server with a FatalError - logs show only the following error which might be related or not to a grinder I'm using recently. Any ideas?

```
[19:30:58] [Server thread/ERROR] [FML/]: FMLIndexedMessageCodec exception caught
java.lang.NullPointerException
        at cpw.mods.fml.common.network.FMLOutboundHandler$OutboundTarget$4.selectNetworks(FMLOutboundHandler.java:109) ~[FMLOutboundHandler$OutboundTarget$4.class:?]
        at cpw.mods.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:273) ~[FMLOutboundHandler.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:115) ~[MessageToMessageEncoder.class:?]
        at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893) ~[DefaultChannelPipeline.class:?]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239) ~[AbstractChannel.class:?]
        at cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:196) [SimpleNetworkWrapper.class:?]
        at com.emoniph.witchery.network.PacketPipeline.sendTo(PacketPipeline.java:50) [PacketPipeline.class:?]
        at com.emoniph.witchery.common.ExtendedPlayer.sync(ExtendedPlayer.java:778) [ExtendedPlayer.class:?]
        at com.emoniph.witchery.common.ExtendedPlayer.fillBloodReserve(ExtendedPlayer.java:451) [ExtendedPlayer.class:?]
        at com.emoniph.witchery.common.GenericEvents.onLivingDeath(GenericEvents.java:1723) [GenericEvents.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_789_GenericEvents_onLivingDeath_LivingDeathEvent.invoke(.dynamic) [?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
        at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:303) [ForgeHooks.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:891) [sv.class:?]
        at net.minecraft.entity.passive.EntityVillager.func_70645_a(EntityVillager.java:335) [yv.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:855) [sv.class:?]
        at com.brandon3055.draconicevolution.common.tileentities.TileGrinder.killNextEntity(TileGrinder.java:167) [TileGrinder.class:?]
        at com.brandon3055.draconicevolution.common.tileentities.TileGrinder.func_145845_h(TileGrinder.java:108) [TileGrinder.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1939) [ahb.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

**Comment by brandon3055** [comment] 2015-04-18 02:03
It looks like it may be related to a witchery mob being killed by the grinder. Any idea what mob that may be?

Also please give the entire crash report. Preferably using pastebin or some other file site.

**Comment by barsch** [comment] 2015-04-18 02:13
was using MFR auto spawner to spawn villagers - so it could be a witchery villager

concerning report: that is pretty much all I got - this message above repeats multiple times in the logs during the time I got disconnected - server didn't crash but kicked all clients - could login again after a while (without server restart)

**Comment by brandon3055** [comment] 2015-04-18 02:31
I will look into it.

**Comment by brandon3055** [comment] 2015-05-07 08:14
Haven't been able to reproduce this problem so i am going to close this issue for now. Let me know if it happens again.

**Closed by brandon3055** 2015-05-07 08:14 UTC
