### ISSUE TITLE
Compatability with Iron Backpacks?

### ISSUE THREAD

**Issue by davelien** [brandon3055/Draconic-Evolution#527] opened 2017-01-05 00:35 UTC
DE: 1.10.2-2.06.157
Brandon's Core: 1.10.2-2.1.3.82-universal
MC: 1.10.2

Also, Iron Backpacks: 1.10.2-2.2.22

I used a mod called Iron Backpacks to automatically sort items that I mine.  When I use a Wyvern pick in 1x1 mode items are automatically inserted into my IB backpack, as expected.  But when I set the pick to do anything more than 1x1 the blocks end up in my inventory.  The Wyvern pick has been updated to Wyvern level and is capable of mining at up to 7x7.

**Comment by DipsWW** [comment] 2017-01-05 17:36
Yhea, im having this issue aswell. Its because when you mine in a 3x3 or higher the items drop as a "blob" to reduce lag, so basically you arent picking up items but the "blob" and that unwraps into items after entering your inventory. You would have the same issue with the Equivalent Exchange tools, because these does the same thing.

It would probably be more reasonable to ask the developer of Iron Backpacks if he could figure out a way to add compatability, maybe he could add a "blob" upgrade, that makes it so "blobs" enter the backpack.
The only way I see it possible for draconic evolution to fix this issue, would be to remove the "blob" feature all together.

**Comment by davelien** [comment] 2017-01-05 18:14
> It would probably be more reasonable to ask the developer of Iron Backpacks if he could figure out a way to add compatability, maybe he could add a "blob" upgrade, that makes it so "blobs" enter the backpack.

I will post this question to the Iron Backpacks developer.  Thanks for the information @DipsWW, I had not noticed that DE dropped dropped materials as "blobs" when mining in anything bigger than 1x1.

**Comment by Tarphoun** [comment] 2017-01-10 02:32
I have same issue with Iron Backpack. not picking up loot or voiding cobblestone. Is there a way to turn off the "blob" mode for AE mining in cfg? i did't see an option. Not being able to auto void cobble is making this package kinda unusable you end up cleaning your inventory more then mining. I went back to the Drill from AA. sad cause i love the draconic gear. I tried the Null charm from Dark utilities as well for voiding, same result.

**Comment by Tarphoun** [comment] 2017-01-10 03:26
> It would probably be more reasonable to ask the developer of Iron Backpacks if he could figure out a way to add compatability, maybe he could add a "blob" upgrade, that makes it so "blobs" enter the backpack.

> 
I'm not sure I agree with this. The issue is not only with Iron backack but also the Dark Utilities Null Charm and probably other similar items that try to "process items as they enter the inventory".

On a side note i found a way around the issue. I'm using a "Player Chest" from ExtraUtils2 and pulling cobble and other stuff out of my inventory as they enter it. 5x5x5 mining is great!

**Comment by davelien** [comment] 2017-01-17 18:27
Please see https://github.com/gr8pefish/IronBackpacks/issues/142 for additional information regarding `ItemPickupEvent0` (or `EntityItemPickupEvent`).

**Comment by brandon3055** [comment] 2017-02-06 18:50
This should be fixed in the next release.

**Closed by brandon3055** 2017-02-06 18:50 UTC
