### ISSUE TITLE
Lag in MainMenu

### ISSUE THREAD

**Issue by Tsunayoshi** [brandon3055/Draconic-Evolution#118] opened 2015-07-11 03:22 UTC
Hi there,

I have noticed, that I have a freezed minecraft process after the mojang/forge loadingscreen. It takes ~30sek until the process unfreezes and I can click on the buttons in the menu.

Ich have broken down my modpack with 280mods, down to:
Draconic-Evolution-1.7.10-1.0.1c

I have noticed this lag since may 9th. But couldn't tell where it comes from.
I hope you can fix it.

**Comment by brandon3055** [comment] 2015-07-22 10:09
This is something i am aware of although this sounds like a very extreme case because usually its only 3-5 seconds. The issue is DE reloads all textures when the game loads but this should not take 30 seconds... While in game press F3+T (this will manually reload all textures) and let me know how long the game freezes. Maby your computer just takes longer then normal to load the textures but in any case i plan to have this fixed in the next release.

**Comment by Tsunayoshi** [comment] 2015-07-22 22:02
Hey,
the F3+T took ~45sek. It's the same time as in the mainmenu.

I am using:
CPU i7 3770 @3,4GHz
Java 1.8.0_40 64Bit
Xmx 6GB
Xms 2GB
PemSize 256MB
The Minecraft files are all on a Raid 0 of 2 SSDs

The Soartex Texturpack (with all mods) http://minecraft.schuby.net/downloads/Soartex.zip [~255MB]
An my Modpack has about 280 Mods in it. Maybe it is the mass of mods, that causes it?

A nearly fitting mod list is here: http://minecraft.schuby.net/server/mod.php (Not all are installed anymore, but only 3 or 4)

**Comment by XFactHD** [comment] 2015-07-23 09:48
@Tsunayoshi Try to use higher Xmx size if you can. I am playing a modpack with approximately 200 mods, I am using 10GB Xmx and the game is still lagging.

**Comment by Tsunayoshi** [comment] 2015-07-23 16:54
If have tested it with 10GB, but it took 5sec longer. I think the time to address more than 8GB costs more time over all.
I have not really a problem with lags ingame (optifine does a good job here). it's only on the first load, entering the main menu (or forcing it with f3+t).
Removing DE solves this problem, but I don't want to be without it :wink: 

So I will wait for the fix. I am not in a hurry :smile:

**Comment by brandon3055** [comment] 2015-07-28 11:46
You shouldnt need more then 4 to 5GB ram unless there are some memory leaks in the pack.
If i had to guess i would say its probably the resource pack because higher res textures will take longer to load. In any case this is now fixed in dev and i hope to have a release out some time within the next 2 weeks but dont hold me to that because it may be longer.

**Closed by brandon3055** 2015-07-28 11:46 UTC
