### ISSUE TITLE
Ender IO no longer receives power from DE wireless crystals.

### ISSUE THREAD

**Issue by insectdude1258** [brandon3055/Draconic-Evolution#1146] opened 2018-07-26 20:05 UTC
#### Issue Description:
Draconic wireless energy crystal will not stay bound to or provide power to ender i/o machines, but does work with other modded machines.

#### What happens:
Upon connecting with wrench, the beam will show for about 5 seconds and then disappear. No energy will be provided to the machine.

#### What you expected to happen:
Binding wireless energy crystal to Ender I/O machines should link and provide power.

#### Steps to reproduce:

1. Set up any power source
2. Put Draconic Evolution Energy I/O Crystal (any tier) on said power source
3. Bind Draconic Evolution Energy I/O Crystal to Draconic Evolution Wireless Energy Crystal
4. Bind Wireless Energy Crystal to any Ender I/O machine that accepts power

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.29
- EnderCore: 0.5.35
- Minecraft: 1.12/1.12.2
- Forge: 14.23.4.2707 and 14.23.4.2732

#### Detailed Explanation

In a SP world, I used a EIO creative capacitor with all tiers of I/O crystals and linked it to all tiers of wireless crystals and attempted to link them to EIO machines as well as a machine from another mod (actually additions) as a known working variable. It worked in DW20 pack version 2.0.0, and is broken in pack version 2.1.0

I have tested the mod versions. It is the Ender I/O update that caused the incompatibility.

I updated only Ender I/O (and dependencies) in the prior pack version, and was unable to link the machines. I reverted and instead updated only DE (and dependencies), and it is able to power and link fine.

The issue seems to be with the update of ender i/o and endercore to versions 5.0.29 and 0.5.35 respectively. 
I have posted on DW20 pack page and EnderIO page (they say the problem is with DE not EIO.  That DE uses RF and not FE and therefore should not have worked ever)

**Comment by insectdude1258** [comment] 2018-07-26 20:33
Why does it accept power just fine when using a draconic I/O crystal attached to the machine but not wireless? It's only with the wireless that it doesn't work anymore. Notice in picture the blue line shows power going to the I/O crystal and the capacitors show they are getting power from it. The red line shows the wireless link, which disappears after a few seconds and provides no power.

![2018-07-26_13 28 51](https://user-images.githubusercontent.com/24449926/43286951-5baa2130-90d8-11e8-825b-9beef0d99f2b.png)

**Comment by insectdude1258** [comment] 2018-07-26 20:47
Here is the 2.0 version of DW20s pack. As you can see, the wireless link is indeed providing power to the capacitor without the need of an I/O crystal to receive.
![2018-07-26_13 46 20](https://user-images.githubusercontent.com/24449926/43287575-4f8fa6de-90da-11e8-95d1-eb3ef7a9fe78.png)

**Comment by covers1624** [comment] 2018-07-26 22:39
Duplicate of #1129

**Closed by covers1624** 2018-07-26 22:39 UTC
