### ISSUE TITLE
FTB Infinity, Bug Occuring

### ISSUE THREAD

**Issue by kingkj52** [brandon3055/Draconic-Evolution#148] opened 2015-08-26 02:55 UTC
Sun Dial bug, the days and nights keep flying by, even after breaking the sun dial. I used a daylight sensor and simple inverter (redstone to a block, with a redstone torch on the other side) and the sun dial beside the torch, to auto skip nights. someone broke the torch and moved it to the top of the blog (e.g. turned the sun dial off), I came back hours later and replaced the torch back where it was before. It is now bugged out, breaking the block doesn't fix it. It is on a server. The setup is surrounded by an RFTools shield (projector) to protect it from mobs, if that matters. I do not yet know if restarting the server fixes it, as the owner is not here at the moment to restart it.

**Comment by GreatOrator** [comment] 2015-08-26 03:00
That would most likely be due to a server fault because someone put it on constant run, server restart should fix it, if not get a log from the server admin

**Comment by kingkj52** [comment] 2015-08-26 03:08
It bugged out right after placing the torch back. We are awaiting the server admin to come back and restart. I'll let you know what happens. Great mod, by the way. The last modded minecraft I played was tekkit classic (back when it was just the technic pack) and am loving draconic evolution and everything. Really well done stuff. And amazing response time. Thanks a ton.

**Comment by kingkj52** [comment] 2015-08-26 03:28
Server restart fixed it. As long as it is chunk loaded, and I have an inverter so it only runs at night, it shouldn't break, right? Someone broke the torch and moved it so it wasnt on at all, then I placed the torch back (re-enabling the inverter set up for the daylight sensor) and it just kept going from there.

**Comment by GreatOrator** [comment] 2015-09-03 12:52
Closing since confirmed server restart fixed.  Not a mod bug, just servers can't handle long-term time changing

**Closed by GreatOrator** 2015-09-03 12:52 UTC
Labels: bug
