### ISSUE TITLE
opaque block custom render problem?

### ISSUE THREAD

**Issue by cwage** [brandon3055/Draconic-Evolution#289] opened 2016-04-14 00:18 UTC
Hi,

I noticed a weird problem with opaque blocks rendering inverted (or at least oddly) and tracked it down to having draconic evolution particle generators in my inventory. See these screenshots:

http://tmp.quietlife.net/2016-04-13_18.59.27.png

http://tmp.quietlife.net/2016-04-13_19.01.54.png

This is in FTB Infinity Evolved w/ Draconic Evolution 1.0.2-snapshot_9-MC1.7.10, so apologies if this has already been resolved.

**Comment by brandon3055** [comment] 2016-04-17 02:57
The renderer for that darn particle generator is nothing but trouble lol. As i am not able to reproduce it in my dev world its probably also interacting with some other renderer in your pack. As its a fairly minor non game breaking bug i think i will just leave it since i dont feel like tracking down the exact conditions that are causing it. I can at least guarantee that it will be fixed in 1.9

**Closed by brandon3055** 2016-04-17 02:57 UTC
