### ISSUE TITLE
Charm of dislocation disconnects client from server

### ISSUE THREAD

**Issue by PsionicArchon** [brandon3055/Draconic-Evolution#224] opened 2016-01-29 02:22 UTC
Attempting to bind a waypoint from within an RFTools dimension kicks the client from the server.

Using the latest version of Draconic Evolution on the latest version of forge.

To reproduce, simply attempt to commit a waypoint from within any rftools dim. I was using the enhanced charm of dislocation at the time.

**Comment by brandon3055** [comment] 2016-02-02 02:25
I was not able to reproduce this error. I am using the latest version of RFtools and i tryed both singleplayer and multyplayer. Can you supply an error log for the issue? It should show on ether the server or the client console when the error occurs.

**Comment by PsionicArchon** [comment] 2016-02-02 02:59
I'm no longer able to reproduce the issue. Gotta love bugs like this.

I'd originally thought it had something to do with an excessively high dimension id (250+) yet that doesn't appear to be the case.

Odd, I'll update this if it crops up again.

**Comment by brandon3055** [comment] 2016-02-08 06:38
Ok then for now i will close this issue. Reopen it or create a new issue if you get more information.

**Closed by brandon3055** 2016-02-08 06:38 UTC
