### ISSUE TITLE
Flux gate output working as expected?

### ISSUE THREAD

**Issue by Zaflis** [brandon3055/Draconic-Evolution#236] opened 2016-02-10 13:47 UTC
If i set flux gate to 4000 RF/t and then attach a fluxduct to it with 2 creative energycells, i get 8000 RF/t out. Is this like expected, that it only limits each sender separately?

I don't know how RF API works, but i almost blew up my reactor because of it. I had set like 16 creative energycells to cryotheum duct when testing reactor and finally flux gated it to 60k RF/t going into energy injector. So i figured 1 creative energycell with 100k RF/t would be enough... how wrong i was...

Draconic-Evolution-1.7.10-1.0.2-Snapshot_9

**Comment by Zaflis** [comment] 2016-02-10 13:50
And speaking of the reactor, i can't seem to make it produce more power than i'm outputting, now that i see i was actually injecting over 1M RF/t and output only 500k. It was stable at almost 8000 C.

**Comment by Ipiano** [comment] 2016-02-12 17:04
I had an issue similar to this about a week ago; I'm not sure if it's relevant but you may want to take a look at my issue ticket and see if it might be the same issue

**Comment by brandon3055** [comment] 2016-02-16 05:03
It looks like i may need to address this issue after all. The flux gate currently works by simply limiting the amount of RF that can pass through it each tick but it seems the cryotheum ducts must make multiple energy transfers per tick.

**Comment by Divran** [comment] 2016-03-20 00:12
I set my flux gate to transfer 1M rf/t, connected to a massive enderio capacitor bank in one end, and a draconic energy storage with 10B rf in the other end (for testing). Even though it was set to 1M rf/t, it would only transfer 100k rf/t into the capacitor bank. What am I doing wrong?

**Comment by GreatOrator** [comment] 2016-03-20 00:18
As mentioned just above you, it is something that will be looked into.

**Comment by Divran** [comment] 2016-03-20 00:39
Yeah but above me they were talking about sending too much power, but what I get is less power than specified in the gate ui.

**Comment by Zaflis** [comment] 2016-03-20 04:39
Make sure your capacitor banks are all connected to eachother. It's rare but it's possible they form multiple connected multiblocks (test by right clicking each one, and set their input/outputs to max). You can mitigate that by not having active flux capacitors in inventory for example. Instead of fluxgate you can even have a wall of Resonant energycells for example, input from 1 side and output from the other with cryotheum ducts.

**Comment by Divran** [comment] 2016-03-20 12:21
I did check it by clicking the capacitor bank that the flux gate was connected to, and it had 5M rf/t input/output

**Comment by brandon3055** [comment] 2016-03-20 20:36
First off are you using Snapshot 9 or latter (Im going to assume you are)

Try removing the gate from the equation and see if you still get the same results. That will tell you if its the gate or something else entirely.

The following setup transferred 200M RF at 1M RF/t in exactly 10 seconds meaning the flow was indeed 1M RF/t as expected.
http://puu.sh/nNI32/1c4e449833.jpg
Check if you can replicate those results.

**Comment by Divran** [comment] 2016-03-20 20:51
Maybe the problem is with cryo-stabilized fluxducts? 
![image](https://cloud.githubusercontent.com/assets/1485728/13907053/a7a4297e-eee5-11e5-8726-1709528c89f1.png)
as you can see here, with a basic capasitor bank (the max input is of a single capacitor bank is 1000 rf/t), we're actually inputting 3k rf/t due to the fact that the cryo-stabilized fluxducts are sending the power 3 times per tick, as mentioned by brandon3055 in a post above.

However, when we try the same setup using resonant fluxducts (which have more than 1000 rf/t throughput, but they work differently from the cryo-stabilized fluxducts since they do have an internal storage, whereas the cryos don't)
![image](https://cloud.githubusercontent.com/assets/1485728/13907061/eda6a2c6-eee5-11e5-90f4-b88729e18e7f.png)

here we properly get 1000 rf/t

**Comment by wlhlm** [comment] 2016-03-20 21:15
@Divran Interesting investigation! Maybe report here as well: https://github.com/CoFH/Feedback

**Comment by Divran** [comment] 2016-03-20 21:27
Just tried it with a resonant energy cell, and they don't have this problem at all. Since it's from the same mod, they are obviously handling the cryo-ducts properly. Maybe you could check the code for this energy cell to see if they're doing anything differently?

**Comment by brandon3055** [comment] 2016-03-20 21:55
Ok let me just explain whats going on here. With conventional fluxduct the duct itself has an internal energy buffer which each energy provider injects energy into. The duct then ejects energy from this buffer into energy acceptors once every tick.

Cryo ducts work differently. In order to allow infinite energy flow they would require a buffer with infinite capacity so they have no buffer at all. Instead the way they work is whenever an energy provider injects energy into a duct the duct will pass that energy directly to any attached acceptors. So if you have 3 providers each injecting energy every tick and one acceptor the acceptor will receive 3 times the energy it should per tick. (I would consider this a bug)

I fixed this problem (with the gates atleast) in snapshot 9 by adding a max per tick transfer limit.
So my question again is what version of DE are you using?

**Comment by Divran** [comment] 2016-03-20 22:19
Yep that's exactly how i thought they worked. It is possible I'm using a slightly outdated version, can't check right now. That's great if you've fixed it. However this is still an issue with cryo ducts and should probably be fixed on their end. I assume that energy conduits have the ability to retrieve the max input rate of the block they are trying to input into? If so it should be easy for them to limit the amount of energy that is transferred into each block each tick.

**Comment by brandon3055** [comment] 2016-03-20 22:25
assuming the transfer rate of the conduit is high enough to support the transfer rate of the block yes.

**Comment by Divran** [comment] 2016-03-21 07:19
Well if it isn't then there's no need to limit it

**Comment by brandon3055** [comment] 2016-03-21 13:50
Yes i did... It should be fixed in that version.

**Comment by Divran** [comment] 2016-03-21 16:34
Just checked, and that is definitely the name of the jar file. You could try downloading "FTB Infinity Evolved" yourself and have a look.

**Comment by brandon3055** [comment] 2016-03-23 05:24
I am running a slightly older Evolved version and cant update atm but i am running DE snapshot 10 and i was not able to reproduce the issue.
http://puu.sh/nQFDC/cbac9ebb6d.png
http://puu.sh/nQFEA/6a1bdc8cfe.jpg
http://puu.sh/nQFF8/a0ac60b3cd.png

**Comment by Divran** [comment] 2016-03-23 08:45
Alright so we just have to wait for FTB to update the infinity pack I guess

**Comment by TyTyKnee** [comment] 2016-04-06 12:56
Alright, so I'm having a similar yet somewhat different issue with the flux gate. My induction cell (Mekanism) seems to amplify the effect, making it not 3x faster, but 101x faster then it's supposed to. It only happens when using cryo-fluxducts similar to the rest. 

What the flow should be:
![2016-04-06_07 46 46](https://cloud.githubusercontent.com/assets/18307736/14317097/2f8b4bcc-fbcc-11e5-9f00-d6c66db09ccf.png)

What it actually is:
![2016-04-06_07 46 58](https://cloud.githubusercontent.com/assets/18307736/14317133/61ea6b48-fbcc-11e5-990e-642f49642a0a.png)

Thought this could be useful for you, for now I'll just make do. 

Mod Versions:
Thermal Dynamics 1.1.0
Mekanism 8.1.8
Draconic Evolution 1.0.2 - Snapshot 9

**Comment by brandon3055** [comment] 2016-04-06 13:13
So yea same issue. So if you have 3 inputs to the duct and 1 output you will get 3x the output you should. If you have 10 inputs the output will be 10x. So im guessing you have 101 separate sources supplying the duct in your case.

**Comment by TyTyKnee** [comment] 2016-04-06 13:17
Well it's only 1 output, the Induction Matrix. I'm guessing it attempts to input energy 101x each tick, otherwise I don't have a clue.

**Comment by Zaflis** [comment] 2016-04-06 13:21
How many output providers do you have inside the matrix? It looks really big.

**Comment by TyTyKnee** [comment] 2016-04-06 13:24
Only 2, I tried different sizes and providers and ports and no matter what it gives the 101x effect.

This is the one I'm using in my world and it does the same thing
![2016-04-06_08 19 56](https://cloud.githubusercontent.com/assets/18307736/14318005/81eb4bf2-fbd0-11e5-9ac2-b443ac4d224b.png)

**Comment by brandon3055** [comment] 2016-04-17 05:44
I think we have concluded that this is a CoFH bug. It should atleast be fixed for the flux gates in the latest versions of DE.

**Closed by brandon3055** 2016-04-17 05:44 UTC
