### ISSUE TITLE
Still [WIP]?

### ISSUE THREAD

**Issue by Micro-Steve** [brandon3055/Draconic-Evolution#411] opened 2016-10-15 10:44 UTC
I have 2 issues but not sure where they fall.
1) When I open up the in-game manual all I get is information about Project Intelligence.
2) Unable to upgrade my Wyvern sword from basic to Wyvern...Says the level is too high for this sword.????
I just upgraded to the latest Draconic and Brandons core builds.  No change from the previous builds.

**Comment by brandon3055** [comment] 2016-10-18 17:32
Project Intelligence downloads its documentation from this github repo. Do you know of any reason your minecraft instance would not be able to connect to the internet? If not please give me the full minecraft log.

You can also download the documentation manually from here: https://github.com/brandon3055/Project-Intelligence-Docs/archive/master.zip
Put the ModDocs folder in config\brandon3055\ProjectIntelligence

As for the other issue. That will be fixed in the next release.

**Comment by Micro-Steve** [comment] 2016-10-18 19:27
Well that was interesting.  I moved the ModDoc folder as you said and still nothing.  I went back again and  moved the Draconicevolution XML Document intro the ModDoc folder and now it shows in game.

As for if I am connected to the internet I can only assume yes.  I put my Mod Pack together on the Curse Site and log in from there.  I do receive Mod update info so i guess it pings at least once.

I am new to Pastebin as such but am unable to get my log info pasted there.  Maybe too large?  Still trying to figure that out.  I am such a noob.  lol

As for the sword, thanks.  I have already advanced it to the Draconic level with no issues.

**Comment by MCTyler** [comment] 2016-10-18 23:41
Seems that some of the Energy Items are missing like the transceivers and I can't get the Energy Pylons to collect energy. I set it up as Per the Video on your webpage. Forge 2099, Brandon Core 51, Draconic 107 Universal, Its keeps griping that I need the old Version of Chickencorelib, but I have the latest. Heres a Pic of my Setup....[[Imgur](http://i.imgur.com/jgYJZ3q.png)](url)

**Comment by brandon3055** [comment] 2016-10-19 06:40
@MCTyler I can only see 2 of the pylons but the 2 i see are in output mode meaning they take energy out of the core and insert it into attached machines/cables To switch the mode just right click the blue sphere on top of the pylon.

The energy transfer system has not been re implemented yet.

**Comment by MCTyler** [comment] 2016-10-19 09:15
Ok, Yea I figured that out after looking at it, Works as intended... Great Mod! Looking forward to the wireless aspect since the tesseract has been removed.

**Closed** 2016-10-25 16:24 UTC
