### ISSUE TITLE
Fusion Crafting Animation not showing

### ISSUE THREAD

**Issue by ConnorPr** [brandon3055/Draconic-Evolution#810] opened 2017-06-29 10:24 UTC
## Description

The animations for Fusion Crafting are not showing. The crafting does work and after a few seconds, the end result shows up in the Crafting Core (forgot the name) and it works fine and uses energy, the animation just isn't showing.

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 1.10.2-forge1.10.2-12.18.3.2316

**Comment by brandon3055** [comment] 2017-06-29 20:58
Your not the first to report this but so far i have been unable to reproduce this in dev which makes it tricky to actually fix. I made some changes that may fix this in the next release. So let me know if this is fixed or not when i push the next version.

**Comment by brandon3055** [comment] 2017-06-29 21:04
Found it! turns out this only happens when you have the injectors 1 block from the core which is why i could never reproduce the issue. This will be fixed in the next release.

**Closed by brandon3055** 2017-06-29 21:04 UTC
