### ISSUE TITLE
Energy transceiver issues on world load when placed on TE items.

### ISSUE THREAD

**Issue by NolanSyKinsley** [brandon3055/Draconic-Evolution#313] opened 2016-05-08 16:45 UTC
If an energy transceiver is placed in a TE energy cell or fluxduct, after the world is saved and reloaded, transparency becomes broken for many textures in the world when looking at certain angles.

Breaking and re-placing the transceivers fixes the issue, but having to do that every time the world loads is rather tiring.

## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: 7.99.40.1614
* Draconic Evolution version: 1.0.2d

## Mod List or Mod Pack (include version)
Infinity Evolved: Skyblock 1.1.0 (This pack has fastcraft, I have tested both with and without, the issue is still present) 

## Other mods being used
TCBotaniaExoflame 1.4
applecore 1.3.0

No crash report but images:

The two transceivers causing the issue http://i.imgur.com/tERZqK5.png and http://i.imgur.com/pAgqJGv.png (Note in the last picture, the white helmet on the armor stand is actually a scuba helmet from buildcraft. This is also a result of the bug and reverts to normal when I remove the two transceivers and replace them.)

This shows the effect of the bug on transparent textures: http://i.imgur.com/NYyltVy.png (the transceivers are below this farm)

**edit**
It seems I have to break and replace all transceivers to fix the issue, not just those on TE items.

**Comment by GreatOrator** [comment] 2016-05-08 17:23
Aye, this is a bug in the custom rendering for those items.  As far as I am aware, it is a bug unfortunately that may not be fixed in 1.7.10 though brandon is nearly completely rewriting DE for 1.9, including the rendering code.

**Comment by NolanSyKinsley** [comment] 2016-05-08 22:26
I tried separating them with an enderio conduit and that did not solve it. Seems it is not just TE items either, just that they are powered when the world loads. Even leaving the area and returning causes it.

**Comment by brandon3055** [comment] 2016-05-16 11:27
I was not able to reproduce this issue in my test world or on a server running SkyBlock but i think i may have found the problem anyway. If you can i would appreciate it if you could test this version in your world and see if it is fixed http://puu.sh/oTP1Y/d3b42bfafd.jar

**Comment by NolanSyKinsley** [comment] 2016-05-18 00:53
That resolves the issue! Thank you so much!!

**Comment by brandon3055** [comment] 2016-05-18 02:02
Awesome! I should be pushing that update some time this week after a make a couple other minor changes.

**Closed by brandon3055** 2016-05-18 02:02 UTC
