### ISSUE TITLE
Shovel of the Wyvern can't dig up Cursed Earth in a 3x3 area

### ISSUE THREAD

**Issue by Jukari** [brandon3055/Draconic-Evolution#40] opened 2015-03-23 00:44 UTC
Using FTB Infinity 1.2.1 pack, Draconic Evolution 1.0.1 snapshot 3, whenever I try to dig up cursed using the 3x3 area, it gets to where the block almost breaks, then it resets the progress and starts over.  Switching to 1x1 fixes it to do individual blocks, not sure if this is a bug or intended, but figured I'd report it.

**Comment by brandon3055** [comment] 2015-04-16 01:52
Oh sorry looks like i forgot to reply to this issue. I have confirmed the bug is a problem with DE and i should have it fixed by the final 1.0.1 release.

**Closed by brandon3055** 2015-04-16 01:52 UTC
