### ISSUE TITLE
Slow mob grinder

### ISSUE THREAD

**Issue by sirzento** [brandon3055/Draconic-Evolution#954] opened 2017-11-01 19:35 UTC
## Description
I use the mob grinder for years but we start a new world with a other modpack and now the mob grinder is slow. If a mob spawns it takes 5-6 sek till the mob grinder kills the mob.

I tried different distances and multiple grinders with no change.

In singleplayer, if I spawn skeletons every 1 sek 2 blocks away from the grinder, like 80% will die instant but the 20% takes 5 seks. That not good If you want to make a wither farm.

The server is not lagging and also not my pc.

A video of this happen: https://youtu.be/oOlKiNfc67Y

## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: 10.13.4.1614
* Mod Pack: Beyond the Infinity (Infinity Evolved with a few more mods)

**Comment by KamranMackey** [comment] 2017-11-02 02:08
I highly doubt Brandon is going to release an update to fix this considering the MC version is 1.7.10 and the last DE update for 1.7.10 was released in July of 2016.

**Comment by brandon3055** [comment] 2017-11-07 16:53
This is not a bug the grinder has always worked like this. If the grinder does not find any mobs to kill it will wait 5 seconds before scanning again. This is not a problem with withers because it detects them during there spawning phase which is a lot longer than 5 seconds then it insta-kills them as soon as they finish spawning.

**Closed by brandon3055** 2017-11-07 16:53 UTC
Labels: 1.7.10 - outdated, working as intended
