### ISSUE TITLE
Fusion crafting "Charging/Crafting" Percents Broken

### ISSUE THREAD

**Issue by AntoRod** [brandon3055/Draconic-Evolution#789] opened 2017-06-18 15:15 UTC
## Description
The Fusion crafting "charging" and "crafting" Percent are broken, it shows you that the charging and crafting take about a second, but it takes the normal time, so you can't know exactly when it's charging or crafting.
I can take a video if you want.

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 1.10.2-1285
* Draconic Evolution Version: 1.10.2-2.1.1.236
* Brandons Core Version: 1.10.2-2.1.8.107

**Comment by NoplixDE** [comment] 2017-06-20 16:19
Is it like that? 
https://www.youtube.com/watch?v=lH8oyhp8jlU
Just wondering.

**Comment by AntoRod** [comment] 2017-06-29 18:58
yes, exactly the same thing, (sorry the answer ended up in my spam..)

**Comment by rellis32** [comment] 2017-06-29 19:32
For what it's worth - i experienced this while the crafting core was 1 block away from the injector. Moving to two blocks away it displays normally.

**Comment by brandon3055** [comment] 2017-06-29 21:00
@rellis32 Thanks for that this is why i could never reproduce the issue! because i always have my injectors 2 blocks away!

**Closed** 2017-06-29 21:50 UTC
Labels: 1.10.2, bug, fixed, fixed in dev
