### ISSUE TITLE
Energy Pylons stops workin

### ISSUE THREAD

**Issue by Soundmastermatt** [brandon3055/Draconic-Evolution#552] opened 2017-01-21 18:07 UTC
I have 1 tier 6 storage, and 1 tier 7 (from here on will be call 6 & 7).  

The two storage's are 4 chunks (diagonal) apart. 
![2017-01-21_12 28 48](https://cloud.githubusercontent.com/assets/25268748/22176356/65fec1ea-dfd6-11e6-94d2-4e5e8ce78205.png)

7 is my main, it is the one I feed my base from. 6 is in the ceiling of my power room. 

I am using extra utilities generators, producing ~75k r/t. All gens are connected to 6 via EPs (energy pylon). There are six EPs. I use the pylons instead of running power lines. 
![2017-01-21_12 29 05](https://cloud.githubusercontent.com/assets/25268748/22176362/789e7246-dfd6-11e6-91a5-1c1f4d470c2d.png)

The output of 6 to 7 is the problem.

On 6 I four EPs feeding 8 side of rftool power cells. Which gives a through put of 240k r/t.
![2017-01-21_12 38 37](https://cloud.githubusercontent.com/assets/25268748/22176371/9c063c96-dfd6-11e6-8f1b-d04221f49169.png)

On 7 I have the same through put.
![2017-01-21_12 27 57](https://cloud.githubusercontent.com/assets/25268748/22176372/9fd551d6-dfd6-11e6-8298-5af504d23a4d.png)

All chunks are kept loaded by extra utilities chunk loader (also tried ftb utilities chunk loader). I have not seen any evidence of chunks not loaded.

If I log off the server, or if I go to work on my tree farm (about 300m away). When I come back to look at 7 I have no input power. So, I brake the glass on 6's output EPs and the glass on 7's input, or the gen's EPs to get it to work.

**Comment by Phishinabowl** [comment] 2017-01-23 14:11
I've noticed the exact same problem in my world. Playing on latest DW20 1.10 pack (v1.4.1) and everytime I log back in after a few hours offline I have to break and replace my input energy pylon for my main DE energy storage. If I open the GUI it'll show its losing power and the generators will wind up backing up on power. Sometimes it will fix if I shift right click the pylon to see what core its connected to but usually I have to break and replace both the pylon and glass to get power going in again. Sometimes the power from the gen's will actually not back itself up and will start shoving energy into what looks like nowhere...very strange issue.

**Comment by Soundmastermatt** [comment] 2017-01-23 16:49
Good to hear this is a bug. I thought I was staying logged on for 48 was crazy. But, it the only way to keep my base powered.

**Comment by mrgreaper** [comment] 2017-01-23 18:49
I noticed a similar issue with the out energy pylon on my tier 8 the crystals on it charge, to about 7Mil rf then just slowly discharge and despite the core having power (several billion) the pylon stops requesting energy

Not tried breaking the glass (the draconic equivalent to turning it off an on again I guess lol) but will try after work

**Comment by Phishinabowl** [comment] 2017-01-30 13:42
Any progress on this? Still having the same issue. Not sure what its related to but its driving me insane having to check on my base every few hrs to make sure I'm still collecting power...

**Comment by Soundmastermatt** [comment] 2017-01-30 18:49
I've been leaving a second account at my base. Only solution that I've found.

**Comment by brandon3055** [comment] 2017-02-04 23:00
Ok so at this point i have been messing with this for over an hour both in dev and on a SF3 server and i have not been able to reproduce this issue even once. Do you know of a reliable way to reproduce this issue in a test world?

There is one issue i noticed while messing around but i dont think its related to your issue. Under certain conditions the energy core gui will show that the core is filling when really it isnt. That was a purely client side issue and only in the core GUI so i dont believe it has anything todo with what you are describing.

**Comment by Soundmastermatt** [comment] 2017-02-04 23:02
if you want I can get you on the server that it is happening on

**Comment by brandon3055** [comment] 2017-02-04 23:04
That wouldnt really help much as i need direct access to the server to debug the issue. What pack is the server running?

**Comment by Soundmastermatt** [comment] 2017-02-04 23:05
Direwolf 20 1.4.1

**Comment by Soundmastermatt** [comment] 2017-02-04 23:05
It started with the 1.4 update

**Comment by brandon3055** [comment] 2017-02-04 23:07
Ahh for some reason i thought you were running SF3 then i realized you did not say what pack you were running.

**Comment by Soundmastermatt** [comment] 2017-02-04 23:14
BTW, Thank you to the recipe change to the tier 8.

**Comment by brandon3055** [comment] 2017-02-04 23:31
Is the server running sponge or some other such plugin system?

**Comment by Soundmastermatt** [comment] 2017-02-04 23:32
Its just whatever curse 1.4.1 is

**Comment by brandon3055** [comment] 2017-02-04 23:37
Hmm... so far i still cant reproduce the issue on a DW20 1.4.1 server. Everything is working perfectly.

**Comment by Soundmastermatt** [comment] 2017-02-04 23:43
My base has gone through many upgrades, and if I don't keep the chunks loaded by a player it will drop. I have buried my second account under my power room. Have had to reset my pylons all week while my second computer was dead last week.

**Comment by brandon3055** [comment] 2017-02-05 00:12
Can you give me a list of everything you have connected to the pylons? Also can you give me a screenshot of the problematic core showing its pylon layout with the chunk grid enabled?

**Comment by Soundmastermatt** [comment] 2017-02-05 00:25
my name on twitch I can give you a tour

**Comment by Soundmastermatt** [comment] 2017-02-05 00:33
I have it replicated. And no I'm not an annoying 13 year old.

**Comment by brandon3055** [comment] 2017-02-05 00:49
By replicated do you mean in a test world? If so can you give me your test world?

**Comment by Soundmastermatt** [comment] 2017-02-05 00:51
no on the server. Its consistent. I've done it multiple times, in the last few minutes.

**Comment by brandon3055** [comment] 2017-02-05 01:07
Ok so let me make sure im not missing anything. T6 core is supplied by several pylons which are connected to generators via Ender Energy Conduit, Energy is being transferred from T6 to T7 via Advanced Powercell's.
And the issue is in thew transfer between the two cores. Is that correct?

If so which end dose the issue occur on? The t6 or t7? Also have you tried bypassing the powercells?

**Comment by Soundmastermatt** [comment] 2017-02-05 01:16
Also it not 1 specific core or pylon. Output pylons don't seen to be the issue, most of the time the input pylons are the problem. It may be one or a few that forget. My current current setup I have 4 set of all 17 Extra Utilities Gens. There is probably 12 or so energy pylons all around the room. I also have 1 tier 8 with 4 tier 7's ( 7 -> 7 -> 7 -> 7 -> 8). Each 7 is conect ected to the next 7 with 1 energy pylon with 4 of your power crystal for a throughput of 120 mil. The connection between the last 7 and the eight is the same except only 3 power ios. The brake is mostly around the second 7 core

**Comment by brandon3055** [comment] 2017-02-05 01:23
Ok i will have to continue debugging this when i get home.

**Comment by brandon3055** [comment] 2017-02-05 06:40
AH HA!! Pylon + Energy crystal = bad. Now to figure out why...

**Comment by brandon3055** [comment] 2017-02-05 12:03
Ok im happy to say this should* be fixed in the next release!

**Closed by brandon3055** 2017-02-05 12:03 UTC
