### ISSUE TITLE
net.minecraft.util.ReportedException: Ticking player

### ISSUE THREAD

**Issue by mistek131995** [brandon3055/Draconic-Evolution#1317] opened 2019-05-17 19:33 UTC
## Base information
* Minecraft version: 1.12.2
* Mod version: Draconic-Evolution-1.12.2-2.3.22.343
* Minecraft Forge version: 1.12.2 - 14.23.5.2838
* Mod Pack: (if applicable)

`
[22:21:43] [Server thread/WARN] [minecraft/NetworkSystem]: Failed to handle packet for /5.18.189.69:5837
net.minecraft.util.ReportedException: Ticking player
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
        at net.minecraft.network.NetHandlerPlayServer.redirect$onPlayerTick$zjb000(NetHandlerPlayServer.java:2056) ~[pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.UnsupportedOperationException
        at java.util.AbstractList.add(Unknown Source) ~[?:1.8.0_211]
        at java.util.AbstractList.add(Unknown Source) ~[?:1.8.0_211]
        at java.util.AbstractCollection.addAll(Unknown Source) ~[?:1.8.0_211]
        at com.brandon3055.draconicevolution.items.tools.DraconiumCapacitor.updateEnergy(DraconiumCapacitor.java:212) ~[DraconiumCapacitor.class:?]
        at com.brandon3055.draconicevolution.items.tools.DraconiumCapacitor.func_77663_a(DraconiumCapacitor.java:195) ~[DraconiumCapacitor.class:?]
        at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:526) ~[aip.class:?]
        at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:363) ~[aec.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:511) ~[aed.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179) ~[vp.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) ~[aed.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?]
        ... 10 more
[22:21:43] [Server thread/INFO] [minecraft/NetHandlerPlayServer]: mistek lost connection: Internal server error
[22:21:43] [Server thread/INFO] [minecraft/DedicatedServer]: mistek left the game
`

**Comment by runescapejon** [comment] 2019-05-18 07:26
Duplicate of https://github.com/brandon3055/Draconic-Evolution/issues/1315

**Comment by gigabit101** [comment] 2019-05-27 10:14
Can I ask what version of the mod you are using?

**Closed** 2019-07-07 13:17 UTC
Labels: fixed, help wanted
