### ISSUE TITLE
[1.10.2] Flux capacitor trying to charge Ender IO buffers stack causes crash

### ISSUE THREAD

**Issue by lupusagax** [brandon3055/Draconic-Evolution#1020] opened 2018-01-15 17:22 UTC
## Base information
* Minecraft version: 1.10.2
* Mod version: 2.1.5.262
* Minecraft Forge version: 12.18.3.2422
* Mod Pack: (if applicable) FTB Beyond 

## Crash report

[crash-2018-01-15_11.56.06-client.txt](https://github.com/brandon3055/Draconic-Evolution/files/1632429/crash-2018-01-15_11.56.06-client.txt)

## Steps to reproduce
With a draconic evolution flux capacitor in the inventory currently set to charge held items or both, switch to hold a stack of one or more Power / Omni Buffers from Ender IO. Crash should occur as soon as you try to switch to holding the Power / Omni Buffers. Other charging items, such as the Thermal Expansion ones do not appear to cause the crash. Holding a single buffer charges it as expected without crashing.

**Comment by covers1624** [comment] 2018-01-16 11:09
This is a EnderIO issue, Closing as duplicate of https://github.com/brandon3055/Draconic-Evolution/issues/1011 Not exactly the same but EIO must have more than one item with this issue.

**Closed by covers1624** 2018-01-16 11:09 UTC
