### ISSUE TITLE
DEShaders class constructor fails

### ISSUE THREAD

**Issue by curiosity-a** [brandon3055/Draconic-Evolution#719] opened 2017-04-22 11:25 UTC
It seems that you don't like to reopen issues. Let's make another one then.

The issue is causing the viewing of the energy crystal in JEI to crash item render (and doesn't crash the game only because other mods do try to handle your errors) as well as causing viewing of the in-game documentation to crash the game completely.

For logs on the former refer to my post in #682, the latter looks pretty similar:

	java.lang.ExceptionInInitializerError
		at com.brandon3055.draconicevolution.client.render.item.RenderItemEnergyCrystal.bindShader(RenderItemEnergyCrystal.java:147)
		at com.brandon3055.draconicevolution.client.render.item.RenderItemEnergyCrystal.renderItem(RenderItemEnergyCrystal.java:130)
		at codechicken.lib.render.item.CCRenderItem.func_180454_a(CCRenderItem.java:86)
		at codechicken.lib.render.item.CCRenderItem.func_184390_a(CCRenderItem.java:167)
		at codechicken.lib.render.item.CCRenderItem.func_175042_a(CCRenderItem.java:211)
		at net.darkhax.bookshelf.client.render.item.RenderItemWrapper.func_175042_a(RenderItemWrapper.java:267)
		at com.brandon3055.brandonscore.client.gui.modulargui.modularelements.MGuiStackIcon.renderBackgroundLayer(MGuiStackIcon.java:52)
		at com.brandon3055.brandonscore.client.gui.modulargui.MGuiElementBase.renderBackgroundLayer(MGuiElementBase.java:345)
		at com.brandon3055.draconicevolution.client.gui.modwiki.moddata.guidoctree.TreeBranchContent.renderBackgroundLayer(TreeBranchContent.java:151)
		at com.brandon3055.brandonscore.client.gui.modulargui.modularelements.MGuiList.renderBackgroundLayer(MGuiList.java:101)
		at com.brandon3055.draconicevolution.client.gui.modwiki.WikiContentList.renderBackgroundLayer(WikiContentList.java:166)
		at com.brandon3055.brandonscore.client.gui.modulargui.ModuleManager.renderBackgroundLayer(ModuleManager.java:188)
		at com.brandon3055.brandonscore.client.gui.modulargui.ModularGuiScreen.renderBackgroundLayer(ModularGuiScreen.java:155)
		at com.brandon3055.draconicevolution.client.gui.modwiki.GuiModWiki.renderBackgroundLayer(GuiModWiki.java:98)
		at com.brandon3055.brandonscore.client.gui.modulargui.ModularGuiScreen.func_73863_a(ModularGuiScreen.java:147)
		at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
		at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
		at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
		at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
		at net.minecraft.client.main.Main.main(SourceFile:124)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
		at java.lang.reflect.Method.invoke(Unknown Source)
		at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
		at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	Caused by: java.lang.RuntimeException: Error compiling shader: ERROR: 0:1: '' :  Version number not supported by GL2
	ERROR: 0:24: 'min' : no matching overloaded function found 
	ERROR: 0:24: 'max' : no matching overloaded function found 
	ERROR: 0:25: '*' :  wrong operand types  no operation '*' exists that takes a left-hand operand of type 'float' and a right operand of type 'const int' (or there is no acceptable conversion)
	ERROR: 0:25: '-' :  wrong operand types  no operation '-' exists that takes a left-hand operand of type 'const int' and a right operand of type 'float' (or there is no acceptable conversion)
	ERROR: 0:25: '*' :  wrong operand types  no operation '*' exists that takes a left-hand operand of type 'float' and a right operand of type 'const int' (or there is no acceptable conversion)
	ERROR: 0:25: 'max' : no matching overloaded function found 
	ERROR: 0:25: 'max' : no matching overloaded function found 
	ERROR: 0:27: 'min' : no matching overloaded function found 
	ERROR: 0:27: '*' :  wrong operand types  no operation '*' exists that takes a left-hand operand of type 'const float' and a right operand of type 'const int' (or there is no acceptable conversion)
	ERROR: 0:29: '=' :  cannot convert from 'const int' to 'float'
	ERROR: 0:32: 'pow' : no matching overloaded function found 
	ERROR: 0:33: '+' :  wrong operand types  no operation '+' exists that takes a left-hand operand of type 'const int' and a right operand of type 'float' (or there is no acceptable conversion)
	ERROR: 0:33: 'max' : no matching overloaded function found 
	 
		at codechicken.lib.render.shader.ShaderProgram.attach(ShaderProgram.java:105)
		at codechicken.lib.render.shader.ShaderProgram.attach(ShaderProgram.java:82)
		at codechicken.lib.render.shader.ShaderProgram.attachFrag(ShaderProgram.java:73)
		at com.brandon3055.draconicevolution.client.render.shaders.DEShaders.initReactorShader(DEShaders.java:59)
		at com.brandon3055.draconicevolution.client.render.shaders.DEShaders.<clinit>(DEShaders.java:44)
		... 26 more

Note that shaders are turned off in the config.

**Comment by brandon3055** [comment] 2017-05-03 16:38
If an issue needs to be reopened you need to do it yourself. This will be fixed in the next release. The problem is you are running OpenGL 2 but shaders are only supported by OpenGL 3+ and it looks like i forgot to check if shaders are supported before initializing them.

**Closed by brandon3055** 2017-05-03 16:38 UTC
Labels: 1.10.2, bug, fixed in dev

**Comment by curiosity-a** [comment] 2017-05-08 08:02
`If an issue needs to be reopened you need to do it yourself. `
I don't have access to the function. Only the owner and contributors can reopen issues, AFAIK.
