### ISSUE TITLE
Hud elements not showing

### ISSUE THREAD

**Issue by Fluoxi** [brandon3055/Draconic-Evolution#267] opened 2016-03-15 21:32 UTC
I'm playing on the Sky Factory 2 modpack and have recently updated Draconic evolution and BrandonsCore to the latest 1.7.10 versions. After doing so the hud elements from DE won't show anymore. I have tried a lot of different things but I simply cannot make them show up again.

Draconic-Evolution-1.7.10-1.0.2-RC2
BrandonsCore-1.0.0.11
Sky Factory 2.4

http://pastebin.com/aDU87Upw

**Comment by brandon3055** [comment] 2016-03-17 07:48
This is a conflict with Duel Hotbars. I have tracked down the cause and it will be fixed in the next release.

**Closed by brandon3055** 2016-03-17 07:48 UTC
