### ISSUE TITLE
DraconiumChest stoped work forever, furnaceoutputblocked due to transmission speed slower than smelting

### ISSUE THREAD

**Issue by Taokyla** [brandon3055/Draconic-Evolution#1341] opened 2019-07-20 16:41 UTC
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.23.345
* Minecraft Forge version:14.23.5.2838
* Mod Pack: (if applicable)

No  Crash report ,sorry
the draconium chest stop working forever
![image](https://user-images.githubusercontent.com/10359761/61581368-2059cc00-ab50-11e9-8afe-7c433b5772da.png)

AE2, Slower than DE chest
![image](https://user-images.githubusercontent.com/10359761/61581430-af66e400-ab50-11e9-81ca-85529a1856a2.png)

**Comment by brandon3055** [comment] 2019-07-20 23:45
What exactly is the problem? How exactly do you have your IO configured? Are the green slots supposed to be reserved for furnace output? If that is the case then simply disable external input for those slots so they cant be filled by your AE system. 
Or are the red slots configured for furnace output?

**Comment by brandon3055** [comment] 2019-07-21 01:49
Yea... you are going to have to be more specific because this works just fine.
![](https://ss.brandon3055.com/87000)

**Comment by Taokyla** [comment] 2019-07-21 04:02
Sorry to confuse you,I made a simple system to recreate that state.
![J7BaSnrSxg](https://user-images.githubusercontent.com/10359761/61586754-fa631480-abad-11e9-9a6c-05f9de28c535.png)
and my draconium chest setting:
the red part:
![javaw_xkk02NWwX4](https://user-images.githubusercontent.com/10359761/61586765-2d0d0d00-abae-11e9-9ce8-1d5e3ede158a.png)
the greed part:
![javaw_8eS2QxB1Do](https://user-images.githubusercontent.com/10359761/61586760-1797e300-abae-11e9-96ca-158b358fef84.png)
and the unset part:
![javaw_8qilUHZqhV](https://user-images.githubusercontent.com/10359761/61586768-41510a00-abae-11e9-9155-ffd489021121.png)

the chest is attach a me storge bus:
![javaw_xj2hetxdLh](https://user-images.githubusercontent.com/10359761/61586774-66457d00-abae-11e9-932f-d56a63f23116.png)
the buses arround the two diamond chest have four acceleration card
![sGr95r2dqK](https://user-images.githubusercontent.com/10359761/61586783-9e4cc000-abae-11e9-86d0-615d3dec13dd.png)
wait until it happend ,or just take all the acceleration card from the import bus,to make the chest fill of tin ingot, and the draconium chest stop working because of output area is full (It is normal  until now),then add acceleration cards in to the import bus, stop the simulate system,the import bus take all the tin ingot  from the diamond chest and the draconium chest,but draconium chest still stopping work!
![image](https://user-images.githubusercontent.com/10359761/61586794-dc49e400-abae-11e9-946e-d709dbcfb7d2.png)

**Comment by brandon3055** [comment] 2019-07-21 04:48
Ok so in other words the furnace does not detect when an automated process frees up slots and so it gets stuck in the "waiting" state.
Thank you i have been able to reproduce the issue and it should be fixed in the next release.

**Closed** 2019-08-02 13:32 UTC
Labels: fixed
