### ISSUE TITLE
Duping Method With Wyvern Pick

### ISSUE THREAD

**Issue by MrGoobla** [brandon3055/Draconic-Evolution#198] opened 2015-12-12 19:34 UTC
Turn AOE safe mode one. Find a spawner and try to destroy it. It says "Operation was canceled because a title entity was detected." It gives you broken spawners. Sorry for bad wording. Very tired

**Comment by GreatOrator** [comment] 2015-12-12 20:14
What version and what modpack or mods are you using with it?  That sounds like an item from ender i/o so you may need to contact that dev because it sounds like he is using a different method of giving players blocks in regards to spawners.

**Comment by MrGoobla** [comment] 2015-12-12 20:16
I was playing Mad Pack 3. I was hitting a creeper spawner. Then i hit a zombie spawner and it did the same thing

**Comment by wlhlm** [comment] 2015-12-12 22:55
@MrGoobla Can you please explain again exactly what you are doing? I am unable to reproduce this with just Draconic Evolution and EnderIO installed. When I have AOE save mode activated there's no way for me to break the spawner except for setting the size to 1x1 or disabling the mode. And even then I don't get any duped item. How do you break the spawner? So you have any enchants on the pick?

**Comment by MrGoobla** [comment] 2015-12-12 22:56
I will make a video of it.

**Comment by MrGoobla** [comment] 2015-12-12 23:25
@wlhlm https://www.youtube.com/watch?v=pjIcE8mFJMM&feature=youtu.be

**Comment by wlhlm** [comment] 2015-12-13 00:20
Thanks.

I was able to reproduce this (duping) behaviour using the versions of the mods included in Mad Pack 3, namely:

- Forge 1492
- EnderIO 2.2.8.381
- Ender Core 0.1.0.23
- Draconic Evolution Snapshot 5
- Brandons Core 1.0.0.10 (1.0.0.8 as in Mad Pack wasn't available on CurseForge)
- NEI 1.0.5.118 and CCC 1.0.7.47 (just for convenience to get the spawners)

This issue is fixed by updating EnderIO (2.3.0.421), but I'm not sure which version exactly introduced the fix. I recommend [filing this bug for the mod pack](https://forums.atlauncher.com/forum-55.html). Luckily, Draconic Evolution seems to not be at fault here.

**Comment by GreatOrator** [comment] 2015-12-13 00:48
Closing since was identified as ender i/o as mentioned earlier.

**Closed by GreatOrator** 2015-12-13 00:48 UTC
