### ISSUE TITLE
Advanced Dislocator - Cross dimensional travel crashes the server

### ISSUE THREAD

**Issue by tolly7654** [brandon3055/Draconic-Evolution#681] opened 2017-04-04 13:14 UTC
If you use the advanced dislocator and try travel to a different dimension, you will go there, but the server will crash immediately after. In some rare cases, it will dupe the dislocator as well.
Attached is the crash report.
[crash-2017-04-04_15.09.25-server.txt](https://github.com/brandon3055/Draconic-Evolution/files/893226/crash-2017-04-04_15.09.25-server.txt)

**Comment by Viper007Bond** [comment] 2017-05-17 06:46
FWIW, I just used mine to go from the Overworld to the End and it worked fine.

**Comment by cyris69** [comment] 2017-06-07 20:57
Still happening here as well

**Comment by ktole1999** [comment] 2017-06-08 12:25
yes happening here too. i have a player that this happens to when she tp from nether to her base using dislocator. Hopefully this will get fixed soon.

draconic 1.10-2.0.12.222
core 1.10.2-2.1.7.102

sponge 2281-5.2.0-BETA-2253

**Comment by brandon3055** [comment] 2017-06-10 01:00
Im not exactly sure whats causing this. I suggest you also poke the morpheus devs with this because the crash is coming from their event handler and im not sure why.

**Comment by tolly7654** [comment] 2017-06-10 16:56
I forgot to post back here, but we actually went over to Quetzi's github, and it is confirmed it is their fault, not yours brandon. Unfortunately, they're being silly about it and saying that they "won't fix it cos sponge this sponge that and we don't support it". Not sure what to think of it to be honest, but I'm not sure if they're ever going to fix it. I've linked several issues at Quetzi's side that show this issue is happening and that he won't fix it.
Quetzi's issues:
https://github.com/Quetzi/Morpheus/issues/35
https://github.com/Quetzi/Morpheus/issues/21

SpongeForge's issue:
https://github.com/SpongePowered/SpongeForge/issues/830
Someone int he community actually "fixed" it, and tried to distribute a patch for people to use (that guy is awesome), but unfortunately, Quetzi started yelling at him saying he wasn't allowed to do that.

You make your own view and choice on this @brandon3055, but I'm not sure if this will ever be fixed.

**Comment by ktole1999** [comment] 2017-06-10 19:08
Yes I am seeing this mentality with other devs where they are more concerned with their code rather than fixing an obvious bug. We are pulling morphed and going with an alternate mod. Thanks for the update.



Sent via the Samsung Galaxy S® 6, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by tolly7654** [comment] 2017-06-10 20:44
@ktole1999 I have actually given myself a little nickane for each of these cases that pop up. A prime example would be of codeHusky with his loot crate system, and he is what we would call a "dickhead dev". Brandon is quite the opposite of this however :)

**Comment by cyris69** [comment] 2017-06-11 05:18
@ktole1999 What mod are you going to move too? I use it for sleep, tp, and homes.

**Comment by cyris69** [comment] 2017-06-11 05:32
@tolly7654 thanks for the revelation, everything works perfect after removing that plugin, plus the guy seems like a douchenozzle.

**Comment by tolly7654** [comment] 2017-06-11 09:01
@cyris69 Well, he ended up _denying_ a fix that someone else had taken the time to create by saying his mod was All Rights Reserved. Fair enough on the license, but he offered to work with Quetzi to implement the fix into the mod so that we would not have this issue. That's when Quetzi shut him down, and shut down a LOT of other issues with the simple message of "It's sponge, uninstall it!".
These are most of them, but you get the idea. If it has sponge, you get no help.
https://github.com/Quetzi/Morpheus/issues/21
https://github.com/Quetzi/Morpheus/issues/31
https://github.com/Quetzi/Morpheus/issues/32
https://github.com/Quetzi/Morpheus/issues/33
https://github.com/Quetzi/Morpheus/issues/34
https://github.com/Quetzi/Morpheus/issues/35
https://github.com/Quetzi/Morpheus/issues/36

And even [here](https://github.com/SpongePowered/SpongeForge/issues/830#issuecomment-307612829), where @brandon3055 went over to the sponge github and told Quetzi how it could be fixed. THat's probably going to get shut down unless he decides to redeem himself.

**Comment by cyris69** [comment] 2017-06-12 00:07
@tolly7654 I read those last night when I was hopping around his simple "duplicate of x" posts. I'd just like to know what else would he like us to do? I tried doing a simple forge server and nothing works. You can get snapshots of bukkit but those don't work. So anything past 1.7.10 you pretty much have to use sponge and since most people do you'd think he would work on that.

Now the one issue I do encounter and maybe it's just me but overworld mobs freeze once you come back from another dimension. So if I have a portal or just a place set and select it it works fine now, but coming back everything is stuck, I can still punch mobs and kill them, no new ones spawn (at least on my client). Also when breaking blocks they vanish and don't appear on the ground but if you walk over them you get the block (magnets etc do not work). Arrows fire but don't hurt anything and aren't visible at all. Only way to fix this is to reconnect. However, this behavior does not affect other dimensions like the end or nether, though haven't tested RFTools dimensions.

**Comment by brandon3055** [comment] 2017-06-12 18:07
@cyris69 Is that just with the dislocator? Can you try re producing this with other mods like EnderIO?

**Comment by cyris69** [comment] 2017-06-13 01:44
@brandon3055 Yeah, it's just with dislocator. TP mods, RFtools, etc don't cause that issue.

**Comment by ktole1999** [comment] 2017-06-13 12:45
do you have Morpheus mod installed?

**Comment by tolly7654** [comment] 2017-06-17 21:57
Update: @Zidane has self assigned the task at SpongeForge to clean up after Quetzi 😄 
[https://github.com/SpongePowered/SpongeForge/issues/830](SpongeForge Issue)

**Closed** 2017-06-29 21:58 UTC
Labels: 1.10.2, bug

**Comment by TheLargeCactus** [comment] 2018-06-27 07:18
I understand this was closed back in 1.10, but I just experienced this crash in ATM3 when doing the same thing on MC1.12.2 with DE 1.12-2.3.11.290-universal with brandons core 1.12-2.4.2.157-universal
