### ISSUE TITLE
[Multiplayer] Placing the reactor stabilizer crashes server continously

### ISSUE THREAD

**Issue by Scorcher7986** [brandon3055/Draconic-Evolution#333] opened 2016-06-10 12:29 UTC
## Description
I placed the reactor stabilizer down on a multiplayer server without building the rest of the reactor first, and the server instantly crashed. The server continues to crash whenever those chunks are loaded, including whenever I log back in. Doing the same in a singleplayer world works fine.

## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: 1.7.10-Forge10.13.4.1558-1.7.10
* Draconic Evolution version: Draconic-Evolution-1.7.10-1.0.2e.jar

## Mod List or Mod Pack (include version)
1.7.10-MB_Battlegear2-Bullseye-1.0.8.3.jar 
1.7.10_AM2-1.4.0.009.jar 
AnimationAPI-1.7.10-1.2.4.jar 
appliedenergistics2-rv2-stable-10.jar 
backpack-2.0.1-1.7.x.jar 
BiblioCraft[v1.11.4][MC1.7.10].jar 
BigReactors-0.4.1A2.jar 
BloodMagic-1.7.10-1.3.3-17.jar 
Bookshelf-1.7.10-1.0.4.187.jar 
BrandonsCore-1.0.0.12.jar 
buildcraft-7.1.16.jar 
CarpentersBlocksv3.3.7MC1.7.10.jar 
cfm-3.4.8-mc1.7.10.jar 
Chisel-2.9.5.11.jar 
CodeChickenCore-1.7.10-1.0.7.47-universal.jar 
CoFHCore-[1.7.10]3.1.2-325.jar 
ComputerCraft1.75.jar 
CustomMobSpawner 3.3.0.zip 
Damage-Indicators-Mod-1.7.10.jar 
Draconic-Evolution-1.7.10-1.0.2e.jar
DragonMounts-r41-1.7.10.jar 
DrZharks MoCreatures Mod v6.3.1.zip 
DynamicLights-1.7.10.zip 
EnchantingPlus-1.7.10-4.0.0.74.jar 
EnderCore-1.7.10-0.2.0.32_beta.jar 
EnderIO-1.7.10-2.2.8.381.jar 
EnderStorage-1.7.10-1.4.7.37-universal.jar 
EnhancedPortals_1.7.10-universal-3.0.12.jar 
EquivalentExchange3-1.7.10-0.3.507.jar 
extrabiomesxl_1.7.10-3.16.4.jar 
extrautilities-1.2.12.jar 
fastcraft-1.23.jar 
Flans_Mod-1.7.10-4.10.0.jar 
FoodPlus-1.7.2-3.2rS.jar 
gilded-games-util-1.7.10-1.9.jar 
Gollum-Core-Lib-1.7.10.jar 
HardcoreDarkness-MC1.7.10-1.7.jar 
Hats-Mod-1.7.10.jar 
HatStand-4.0.0.jar 
iChun-Util-Mod-1.7.10.jar 
ImmersiveEngineering-0.7.5.jar 
immibis-core-59.1.4.jar 
industrialcraft-2-2.2.820-experimental.jar 
Inventory-Tweaks-Mod-1.7.10.jar 
Iron-Chests-Mod-1.7.10.jar 
Jammy-Furniture-Reborn-Mod-1.7.10.jar 
LIST.bat 
logisticspipes-0.9.3.114.jar 
Mantle-1.7.10-0.3.2b.jar 
Mekanism-1.7.10-8.1.9.265.jar 
MekanismGenerators-1.7.10-8.1.9.265.jar 
Minechem-1.7.10-5.0.5.406.jar 
MineFactoryReloaded-[1.7.10]2.8.1-174.jar 
ModularPowersuits-0.11.0.301.jar 
Morph-Beta-0.9.2.jar 
movingworld-1.7.10-1.8.1.jar 
NetherOres-[1.7.10]2.3.1-22.jar 
NotEnoughItems-1.7.10-1.0.5.120-universal.jar 
Numina-0.4.0.131.jar 
OpenBlocks-1.7.10-1.5.1.jar 
OpenModsLib-1.7.10-0.9.1.jar 
OpenModularTurrets-1.7.10-2.2.2-217.jar 
OptiFine_1.7.10_HD_U_D4.jar 
ProjectRed-1.7.10-4.7.0pre12.95-Base.jar 
ProjectRed-1.7.10-4.7.0pre12.95-Compat.jar 
ProjectRed-1.7.10-4.7.0pre12.95-Fabrication.jar 
ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar 
ProjectRed-1.7.10-4.7.0pre12.95-Lighting.jar 
ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar 
Railcraft_1.7.10-9.10.0.0.jar 
RandomThings-2.2.4.jar 
RedstonePasteMod-1.7.10-1.6.2.jar 
secretroomsmod-1.7.10-4.7.1.413.jar 
SirenMod-3.0.0.jar 
TConstruct-1.7.10-1.8.8.jar 
ThermalDynamics-[1.7.10]1.1.0-161.jar 
ThermalExpansion-[1.7.10]4.1.2-240.jar 
ThermalFoundation-[1.7.10]1.2.3-112.jar 
TMechworks_mc1.7.10_0.2.8.jar 
twilightforest-1.7.10-2.3.7.jar 
witchery-1.7.10-0.24.1.jar 
WR-CBE-1.7.10-1.4.1.9-universal.jar 
Xaeros_Minimap_1.9_Forge_1.7.10.jar 
[1.7.10] SecurityCraft v1.8.1.jar 
CodeChickenLib-1.7.10-1.1.3.138-universal.jar 
ForgeMultipart-1.7.10-1.2.0.345-universal.jar 
ForgeRelocation-1.7.10-0.0.1.4-universal.jar 
ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar 
MrTJPCore-1.7.10-1.1.0.33-universal.jar
EJML-core-0.26.jar 

## Crash report
```
[20:39:54] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: Lcom/brandon3055/draconicevolution/client/render/particle/ParticleReactorBeam;
	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:1.7.0_101]
	at java.lang.Class.privateGetDeclaredFields(Class.java:2509) ~[?:1.7.0_101]
	at java.lang.Class.getDeclaredFields(Class.java:1819) ~[?:1.7.0_101]
	at hats.common.core.HatHandler.isMobSpawner(HatHandler.java:870) ~[HatHandler.class:?]
	at hats.common.core.EventHandler.onEntitySpawn(EventHandler.java:77) ~[EventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_643_EventHandler_onEntitySpawn_EntityJoinWorldEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
	at net.minecraft.world.World.func_72868_a(World.java:3301) ~[ahb.class:?]
	at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:921) ~[apx.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:46) ~[ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12) ~[ChunkIOProvider.class:?]
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189) ~[AsynchronousExecutor$Task.class:?]
	at net.minecraftforge.common.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:354) ~[AsynchronousExecutor.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:30) ~[ChunkIOExecutor.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:596) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.ClassNotFoundException: com.brandon3055.draconicevolution.client.render.particle.ParticleReactorBeam
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_101]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_101]
	... 20 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: net.minecraft.client.particle.EntityFX
	at com.google.common.base.Throwables.propagate(Throwables.java:160) ~[guava-17.0.jar:?]
	at cofh.asm.CoFHAccessTransformer.transform(CoFHAccessTransformer.java:94) ~[CoFHCore-%5B1.7.10%5D3.1.2-325.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_101]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_101]
	... 20 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.particle.EntityFX
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_101]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_101]
	at java.lang.Class.forName0(Native Method) ~[?:1.7.0_101]
	at java.lang.Class.forName(Class.java:278) ~[?:1.7.0_101]
	at cofh.asm.CoFHAccessTransformer.transform(CoFHAccessTransformer.java:90) ~[CoFHCore-%5B1.7.10%5D3.1.2-325.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_101]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_101]
	... 20 more
```

**Comment by brandon3055** [comment] 2016-06-11 14:43
Ok so that is moooostly my fault... But its caused by a very unusual interaction with the hats mod you have installed. Which would be why it hasnt shown up until now. It should be fixed in the next release.

**Closed by brandon3055** 2016-06-11 14:43 UTC
Labels: bug
