### ISSUE TITLE
Crash when oppening Information Tablet

### ISSUE THREAD

**Issue by MCEventHorizon** [brandon3055/Draconic-Evolution#425] opened 2016-10-29 12:07 UTC
Crashlog: http://pastebin.com/TmpC2fsK

**Comment by brandon3055** [comment] 2016-10-30 11:12
That was related caused by me forgetting to update the BC dependency in DE when building that version. It should be fixed in the latest releases.

**Closed by brandon3055** 2016-10-30 11:12 UTC
