### ISSUE TITLE
Several tools bugged and unusable

### ISSUE THREAD

**Issue by ShlohGaming** [brandon3055/Draconic-Evolution#223] opened 2016-01-27 12:05 UTC
While playing FTB Infinity Evolved, I was roaming the Draconic inventory to use my new pickaxe of the wyvern. Upon clicking the little arrow to switch off of the "AOE mining size" screen, my game crashed. Every subsequent attempt to do the same crashes the game, most of the tools are named "Unnamed" and cannot be enchanted. Have not tried digging with tools.

**Comment by ShlohGaming** [comment] 2016-01-27 12:06
http://paste.feed-the-beast.com/view/f4522d9c Forgot to post this with the report

**Comment by GreatOrator** [comment] 2016-01-27 12:50
So looking over the crash, the issue is actually with a mod that is modifying key commands.  I loaded and tested and could not replicate however.

Will wait for brandon to weigh in though, he has a much more intimate knowledge of the code.

**Comment by brandon3055** [comment] 2016-01-28 03:28
As GreatOrator said it looks like an issue with the keybinding. What key do you have assigned to open the gui?

Specifically the issue is when the game tries to look up the human readable key to display in the tool tip where it says "Press <Whatever key is assigned> to open config gui" it is throwing an error because the key assigned is not valid.

Unless you have some weird keyboard configuration or something else i cant even think of chances are another mod is messing with my keybindings.

**Comment by ShlohGaming** [comment] 2016-01-28 04:59
Currently I have it bound to mouse 5 ( a side button on my mouse) But does that explain why, even on the newest version, my tools read as Unnamed and are unenchantable?

**Comment by brandon3055** [comment] 2016-01-28 05:28
Apparently it dose... I seem to get the same issue when i bind it to mouse button 5. But i haven't been able to reproduce the crash although im sure if i tried hard enough i could.... Yea there it is... it happens when you mouse over the item in the config screen.  

I will look for a solution to this when i have the time but for now just dont bind that function to your mouse.

**Closed by brandon3055** 2016-01-28 05:28 UTC

**Comment by GreatOrator** [comment] 2016-01-28 12:13
They may be using the newest version of not enough keys, may want to look into providing support for that as it radically changed the way keybindings are handled

**Comment by brandon3055** [comment] 2016-01-29 01:34
Do i was able to reproduce the error without any other mods installed. To reproduce it just bind the gui key to ether the forward or back button on your mouse (if your mouse has them)
