### ISSUE TITLE
Server Crash. TileEntity CrystalBase, or RF API version in Core?

### ISSUE THREAD

**Issue by kitRyu** [brandon3055/Draconic-Evolution#732] opened 2017-04-29 11:33 UTC
Using a old backup of the world, server crashes.
https://pastebin.com/FJ8rnehq

Using the most updated world, client crashes. (Idk if it is here where I should post this, but client just says an error of conversion ('M' char to... idk.), and the last lines talks about RF API in Brandon's Core... I'm so sorry if I shouldn't post this here.)
https://pastebin.com/HiE61uQw

**Comment by brandon3055** [comment] 2017-05-04 12:27
The first crash should be fixed in the next release. does not seem to be caused by DE. Not sure if its related to the crash but there seem to be a crapload of "itemCoffeeSeed's" in the world.

**Closed** 2017-06-10 00:01 UTC
