### ISSUE TITLE
[Issue] Generators = no output

### ISSUE THREAD

**Issue by BadLucKWyvern** [brandon3055/Draconic-Evolution#1176] opened 2018-09-22 10:26 UTC
## Base information
* Minecraft version:1.12.2
* Mod version:Draconic-Evolution-1.12.2-2.3.13.306-universal
* Minecraft Forge version:1.12.2-forge1.12.2-14.23.4.2757

Ive sticked some generators from Draconic Evolution near Vibrant capacitors from Ender IO,
After fuelling generators, All are producing RF, but the RF isn't going inside EnderIO capacitors
Even if its automatic, ive configured the input/output setup of the capacitor tile, still nothing. 
So ive separated generators and ive linked capacitors and DE Generators with EnderIO cables, Still nothing
Is it linked with the Draconic Reactor problem ?

**Comment by pacman1983** [comment] 2018-09-23 13:56
I'm having the same issue. I've used cryo-stabilized flux duct as well. And the generator isn't pushing the power out. So the saturation goes to 99% and safemode shuts it down. I'm using the FTBRevelation-2.5.0-1.12.2 pack with 

Draconic-Evolution-1.12.2-2.3.13.306-universal


it looks like this issue is fixed in Draconic-Evolution-2.3.14.307 according to the mod release notes
-Fixed AOE mining not taking modified player reach distance into account.
**-Fixed reactor not handling IO sides properly when outputting energy.**
-Attempted top fix broken gui's caused by broken mob souls courtesy of Headcrumbs.
-Fixed Advanced Dislocator not working in portal or pedestal.
-Fixed crash when using CTRL-Pick Block on placed items.

**Comment by brandon3055** [comment] 2018-09-24 22:57
The issue i fixed with the reactor did not effect the generator. As far as i can tell the generator should be working fine.

**Comment by koalalord9999** [comment] 2018-10-29 06:57
IF you guys are using EnderIO in version 1.10+ the reason this no longer works is because enderIO doesn't support RF as a type of energy anymore. You have to use Forge or Tesla energy. I don't know how to convert it at the moment, however. Sorry.

**Comment by brandon3055** [comment] 2018-10-31 14:46
FE is something that mods need to support its not a conversion that can be done by the user.  DE does support FE so im not sure why you are having these issues.

**Closed** 2018-12-18 03:21 UTC
Labels: wtf
