### ISSUE TITLE
Severe Error?

### ISSUE THREAD

**Issue by O13SC3N3** [brandon3055/Draconic-Evolution#34] opened 2015-03-18 03:17 UTC
MC 1.7.10
Draconic-Evolution-1.7.10-v1.0.1-snapshot_5
Forget 1307

[00:37:00] [Client thread/INFO] [Draconic Evolution]: Expanding Potion array size to 256
[00:37:00] [Client thread/ERROR] [Draconic Evolution]: Severe error, please report this to the mod author:
[00:37:00] [Client thread/ERROR] [Draconic Evolution]: java.lang.ArrayIndexOutOfBoundsException
[00:37:00] [Client thread/INFO] [Draconic Evolution]: Finished PreInitialization

**Comment by brandon3055** [comment] 2015-03-18 19:31
Thanks i will look into that. What mod pack/other mods are you using? And have you noticed any issues with potions as a result?

**Comment by O13SC3N3** [comment] 2015-03-18 19:48
Issue sometimes says 358 available or 128 its a little funky on loadups only one that pops out on client side atm is http://pastebin.com/1JjTdNpT

And the mudpack/pack is a custom pack. http://pastebin.com/tJMWNAAf

**Comment by brandon3055** [comment] 2015-03-18 19:54
Ahh i believe it may be a problem with the pack configuration. You are using potion id's all the way up to 250. But the maximum potion id you are allowed to use is 128. This is because on the way minecraft saves effects on mobs. Using higher values will result in some weird and unpredictable results. 
Please correct this error then let me know if you still get the error from DE.

**Comment by O13SC3N3** [comment] 2015-03-18 20:01
Ok ill try, I know I can set a lot of the potions in some of the mods, just brewcraft doesn't really give me the option to do so. Unless I go in manually and find all the ids. Ill do this with witchery first and see what happens.

**Comment by O13SC3N3** [comment] 2015-03-18 20:14
unfortuantly the error still shows, and all potions are under 128 even tho some overwriting a few atm (Any way to extend this limit?) I know RR3 Excessive didn't seem to have this issue. But it doesn't have Draconic Evolution tho. Im a bit lost

**Comment by brandon3055** [comment] 2015-03-18 20:22
Well that error just indicates that DE failed to extend the vanilla potion array. Probably because another mod has already done it. Its likely it wont actually cause any problems. Unfortunately i kinda derped up a bit on that error report so it dosnt actually tell me exactly what the problem is. Let me know if you encounter any problems that could be related to the error.

**Comment by O13SC3N3** [comment] 2015-03-18 20:28
will do thanks for the quick replys, great mod btw!

**Comment by O13SC3N3** [comment] 2015-03-22 05:58
Ok I literally went through all my mods 1 by 1 with Draconic Evolution, Sometimes the error popped up when I didn't see why, even if that damn mod didn't add potions. However I am using Brewcraft (it extends disabled/enabled same deal either way). Random Things does it as well No config to disable or enable, so I removed it entirely. Same thing. Im triple checking all my configs, and mod infos, to see if there is another that does it as well.

**Comment by O13SC3N3** [comment] 2015-03-23 04:52
Biomes O Plenty seems to be the cause. Not Sure how.

**Comment by brandon3055** [comment] 2015-03-23 11:36
I just decided to remove that piece of code for now since i dont actually need it.

**Comment by O13SC3N3** [comment] 2015-04-05 01:32
current update

[04/4/2015 19:27:14 PM] Exception in thread "Thread-12" [19:27:14] [Thread-12/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NoClassDefFoundError: scala/actors/threadpool/Arrays
[04/4/2015 19:27:14 PM] [19:27:14] [Thread-12/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.brandon3055.draconicevolution.client.handler.ResourceHandler$DownloadThread.checkExistence(ResourceHandler.java:154)
[04/4/2015 19:27:14 PM] [19:27:14] [Thread-12/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.brandon3055.draconicevolution.client.handler.ResourceHandler$DownloadThread.run(ResourceHandler.java:92)
[04/4/2015 19:27:14 PM] [19:27:14] [Thread-12/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.ClassNotFoundException: scala.actors.threadpool.Arrays
[04/4/2015 19:27:14 PM] [19:27:14] [Thread-12/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[04/4/2015 19:27:14 PM] [19:27:14] [Thread-12/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[04/4/2015 19:27:14 PM] [19:27:14] [Thread-12/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[04/4/2015 19:27:14 PM] [19:27:14] [Thread-12/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 2 more
[04/4/2015 19:27:14 PM] [19:27:14] [Thread-12/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.NullPointerException
[04/4/2015 19:27:14 PM] [19:27:14] [Thread-12/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[04/4/2015 19:27:14 PM] [19:27:14] [Thread-12/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 4 more
[04/4/2015 19:27:14 PM] [Client thread/INFO] [LiteLoader]: Injecting ons12packetentityvelocity[x1] in func_148833_a in S12PacketEntityVelocity

**Comment by brandon3055** [comment] 2015-04-05 03:52
That has already been reported. It is due to a bug in the code that downloads the images for the new manual. Will be fixed in the next release.

**Closed** 2015-04-16 01:52 UTC
