### ISSUE TITLE
Minecraft 1.12.2 - NullPointerException: Tesselating block model

### ISSUE THREAD

**Issue by 630R63** [brandon3055/Draconic-Evolution#983] opened 2017-12-01 13:07 UTC
## Base information
* Minecraft version: 1.12.2
* Mod version: Draconic-Evolution-1.12-2.3.5.269-universal
* Minecraft Forge version: 14.23.0.2549
* Mod Pack: Modern Skyblock 2 

## Crash report
`java.lang.NullPointerException: Tesselating block model
	at java.util.LinkedList$ListItr.next(LinkedList.java:893)
	at com.brandon3055.draconicevolution.blocks.tileentity.TilePlacedItem.calculateBounds(TilePlacedItem.java:107)
	at com.brandon3055.draconicevolution.blocks.tileentity.TilePlacedItem.getIndexedCuboids(TilePlacedItem.java:175)
	at com.brandon3055.draconicevolution.blocks.PlacedItem.func_185496_a(PlacedItem.java:140)`
....... The rest is in the provided log.
</br>
[crash-2017-12-01_14.41.30-client.txt](https://github.com/brandon3055/Draconic-Evolution/files/1521652/crash-2017-12-01_14.41.30-client.txt)

I have a few items placed in the world using the Draconic Evolution placement. Every once in awhile I get this crash when interacting with the GUI of a device (doesn't matter which one). I imagine this will be hard to replicate as it doesn't occur every time when you open a GUI.

**Comment by 630R63** [comment] 2017-12-02 11:19
Happened again just now whilst washing gems in a cauldron.

**Comment by ifficles** [comment] 2017-12-13 19:54
This has happened to me as well.  I was harvesting redstone orchids in my overworld.  And then, within about 10 seconds, crash.

full crash log with a mod list - https://paste.ee/p/gTsed

**Comment by ifficles** [comment] 2017-12-14 22:29
Tried downgrading to the previous version of DE, the game crashed halfway through loading.  A crash log can be found here, https://paste.ee/p/wcMKO.  Reinstalled the current version of DE, waiting to see what happens.

**Comment by ifficles** [comment] 2017-12-15 04:37
It just happened again.  I was playing for an hour and had just gotten back from the mob farm, then crash.
crash log - https://paste.ee/p/iPBRt
world download - https://www.4shared.com/s/fkhLZXllxei

**Comment by brandon3055** [comment] 2017-12-21 04:53
This may be fixed in the next update. It looks like the crash is due to some interaction between placed items ant chisels connected textures mod.

**Comment by brandon3055** [comment] 2017-12-21 07:40
Ok new build has been released. When you update keep an eye out for something like this in your console. If/when you see it please give me a copy of your log.
![](http://ss.brandon3055.com/8qn9ux8.png)

**Comment by dannydjdk** [comment] 2017-12-27 20:49
At what point should that text appear in the console? I put together a small pack with just Draconic Evolution 2.3.6.139, Chisel 0.1.1.24 and CTM 0.2.3.9 (and all dependencies) with Forge 2555, placed a few Chisel blocks with connected textures and placed an item against them. It crashed, but the log did not print any debugging information. Just in case they are helpful to you, here are the logs:
Crash log: https://pastebin.com/9mZryH51
Console Log: https://pastebin.com/xR41B8iu
Block was placed after line 186 in log.

**Comment by brandon3055** [comment] 2018-01-05 17:51
This should prevent the crash you are experiencing and instead print the message. No way to know exactly when that crash would occur. If you are still getting the crash than its caused by something else. I did just push an update that fixes an issue with the placed items that may have been related to your issue. I suggest you give it a try.

**Comment by dannydjdk** [comment] 2018-01-06 20:06
It is indeed not crashing with DE 2.3.8.279 and Brandon's Core 2.3.7.140. I could reproduce the crash reliably in the previous version, so I think it's safe to assume it's fixed.

**Closed** 2018-03-05 19:48 UTC
Labels: fixed
